frontend/cypress.config.ts
frontend/cypress.d.ts
frontend/cypress/components/AppHealth.cy.tsx
frontend/cypress/components/Dashboard.cy.tsx
frontend/cypress/components/Loading.cy.tsx
frontend/cypress/components/NotFound.cy.tsx
frontend/cypress/components/Profile.cy.tsx
frontend/cypress/components/RoutesComponent.cy.tsx
frontend/cypress/e2e/spec.cy.ts
frontend/cypress/fixtures/example.json
frontend/cypress/integration/index.spec.ts
frontend/cypress/support/commands.ts
frontend/cypress/support/component-index.html
frontend/cypress/support/component.ts
frontend/cypress/support/e2e.ts
frontend/cypress/tsconfig.json
frontend/package-lock.json
frontend/package.json
frontend/test/index.test.tsx
frontend/tsconfig.json

- added cypress config to the frontend
- pipeline config to follow

[TC-0067] (pt 1) frontend cypress config

---

backend/package.json
backend/src/database/database.module.ts
backend/test/app.e2e-spec.ts
backend/test/app.spec.ts
backend/test/jest.json

- Added backend config for jest
- Runs on local, pipeline config to follow (TC-66)

[TC-0083] (pt 2) jest config

---

CODE-OF-CONDUCT.md
CONTRIBUTING.md
DEV.md
README.md

[TC-0093](https://bcdevex.atlassian.net/browse/TC-0093)
Objective:
- update readme with the standard bc gov format

[TC-0093] readme update

---

backend/Dockerfile.prod
frontend/Dockerfile.prod

[TC-3](https://bcdevex.atlassian.net/browse/TC-3)
Objective:
Add some production dockerfiles. This can be cleaned up later.
[TC-3]: https://bcdevex.atlassian.net/browse/TC-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-3] add production dockerfiles

---

frontend/Caddyfile
frontend/Dockerfile.prod
frontend/cypress.config.ts
frontend/package-lock.json
frontend/package.json
frontend/postcss.config.cjs
frontend/src/main.tsx
frontend/tsconfig.json

[CHORE] prod-css

---

Makefile

Objective:
Command to tunnel into the patroni db so that we can read / add data

[CHORE] add open db tunnel

---

backend/src/app.module.ts
backend/src/database/entities/function.entity.ts
backend/src/function/function.controller.ts
backend/src/function/function.module.ts
backend/src/function/function.service.ts
backend/src/function/ro/function.ro.ts
backend/src/personnel/dto/get-personnel.dto.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.service.ts
backend/src/swagger.ts

[TC-86](https://bcdevex.atlassian.net/browse/TC-86)
Objective:
Endpoint to get all functions so that we can use them on the frontend
[TC-86]: https://bcdevex.atlassian.net/browse/TC-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-86] add endpoint for getting functions

---

backend/src/database/entities/personnel.entity.ts
backend/src/personnel/dto/get-personnel.dto.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/personnel.ro.ts
frontend/src/common/enums/experience.enum.ts
frontend/src/components/form/components/MultiSelect.tsx
frontend/src/components/form/components/Search.tsx
frontend/src/components/layout/Layout.tsx
frontend/src/components/table/Table.tsx
frontend/src/components/table/header/TableFilters.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/constants.ts

[TC-88](https://bcdevex.atlassian.net/browse/TC-88)
Objective:
Backend changes to implement function / experience filters
Fix to work location filter
Frontend fixes to useTable custom hook (now only used in Table, not in TableFilter)
Working filters in frontend
[TC-88]: https://bcdevex.atlassian.net/browse/TC-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-88] working filters

---

backend/src/app.controller.ts
frontend/src/env.d.ts
frontend/src/routes/AppRoutes.tsx
frontend/src/services/api-endpoints.tsx
frontend/src/utils/keycloak.ts

[TC-235](https://bcdevex.atlassian.net/browse/TC-235)
Objective:
While I'm open to doing this through devops, this for me is the path of least resistance.
[TC-235]: https://bcdevex.atlassian.net/browse/TC-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-235] request keycloak info from backend

---

Makefile
backend/package-lock.json
backend/package.json
backend/src/common/utils.ts
backend/src/database/database.module.ts
backend/src/database/datasource.ts
backend/src/database/entities/personnel.entity.ts
backend/src/database/migrations/1706297652551-migrations.ts
backend/src/database/seed-functions.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.service.ts
backend/test/app.spec.ts

[TC-0121](https://bcdevex.atlassian.net/browse/TC-0121)
Objective:
- use makefile cmd to generate seed data
- updated db module in order to run typeorm migrations
- added scripts to run migrations (locally for now - we can also keep syncing I just thought we should get these started ?)

[TC-121] seed data + migrations (for local)

---

.github/workflows/ci-promote-test.yaml

Objective:
Point the test deployment action to test env

[CHORE] promote test GHA env

---

Makefile
backend/src/common/utils.ts

[TC-0121](https://bcdevex.atlassian.net/browse/TC-0121)
Objective:
- Seed script for dev/test

[TC-121]: Seed script for dev/test

---

frontend/src/components/filters/CascadingMenu.tsx
frontend/src/components/filters/MultiSelect.tsx
frontend/src/components/filters/MultiSelectGroup.tsx
frontend/src/components/filters/classes.ts
frontend/src/components/table/Table.tsx
frontend/src/components/table/body/TableBodyCell.tsx
frontend/src/components/table/body/TableBodyRow.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx

Objective:
- update styling to match designs for the table view for func/exp

[FIX]: column style/display for func/exp on dash

---

.gitignore
frontend/Dockerfile.ci
frontend/cypress/support/component-index.html
frontend/src/components/layout/Footer.tsx
frontend/src/components/layout/Layout.tsx
frontend/src/hooks/useGetUserInfo.tsx
frontend/src/routes/PrivateRoute.tsx
frontend/src/styles/typography.css
keycloak/Dockerfile

[TC-0236](https://bcdevex.atlassian.net/browse/TC-0236)
Objective:
- set up sonarcloud (not done in this PR - configured in the sonarcloud UI)
- addressed warnings

[TC-236]: Sonarcloud config + fix warnings

---

backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.service.ts
frontend/src/components/table/body/TableBodyCell.tsx
frontend/src/components/table/body/TableBodyRow.tsx

[TC-0240](https://bcdevex.atlassian.net/browse/TC-0240)
Objective:
- Get personnel by id endpoint
- Added profile/:id redirect on the dashboard when you click name

[TC-240]: BE profile endpoint

---

backend/src/personnel/dto/get-personnel.dto.ts
backend/src/personnel/personnel.service.ts
frontend/src/components/header/Header.tsx
frontend/src/hooks/useTable.tsx

Objective:
- remove 3 char min for search
- ensure page 1 is set for the page param on filter changes

[FIX]: TC-221/TC-217

---

.github/workflows/ci-promote-test.yaml

[CHORE] test pipeline fix attempt

---

frontend/src/components/table/body/TableBodyCell.tsx
frontend/src/pages/profile/DetailsSection.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileHeader.tsx

Objective:
Setting the col span as a variable seems to cause issues in a way that this doesn't. This is a temporary fix for demo purposes, to be honest.
(This is already deployed to dev)

[FIX] attempting to fix columns

---

.gitignore
frontend/src/components/table/classes.ts
frontend/src/hooks/useTable.tsx
frontend/tailwind.config.cjs

[TC-0270](https://bcdevex.atlassian.net/browse/TC-0270)
Objective:
- ui update for union membership values

[TC-270]: fixed union membership flags

---

frontend/src/components/table/body/TableBodyCell.tsx

As per a comment on [TC-230](https://bcdevex.atlassian.net/browse/TC-230)
Objective:
[TC-230]: https://bcdevex.atlassian.net/browse/TC-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX] make names links on dashboard blue

---

frontend/src/components/toggle/Toggle.tsx

Objective:
- my smallest PR on record

[FIX] Input Label

---

backend/src/common/enums/availability-type.enum.ts
backend/src/common/utils.ts
backend/src/database/entities/availability.entity.ts
backend/src/database/entities/personnel.entity.ts
frontend/src/common/enums/availability-type.enum.ts
frontend/src/components/table/classes.ts
frontend/src/pages/dashboard/constants.ts

[TC-0272](https://bcdevex.atlassian.net/browse/TC-0272)
Objective:
- availability mock data
- new column for deployment code

[TC-272]: availability script

---

frontend/src/components/table/header/TableHeader.tsx
frontend/src/pages/dashboard/constants.ts

[FIX] fix headers

---

backend/src/app.controller.ts
backend/src/auth/auth.controller.ts
backend/src/auth/auth.guard.ts
backend/src/auth/interface.ts
backend/src/auth/ro/user-info.ro.ts
backend/src/auth/roles.decorator.ts
backend/src/auth/roles.guard.ts
backend/src/common/enums/endpoint.enum.ts
backend/src/common/enums/status.enum.ts
backend/src/common/utils.ts
backend/src/database/entities/function.entity.ts
backend/src/database/entities/personnel.entity.ts
backend/src/personnel/dto/get-personnel.dto.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/get-personnel.ro.ts
backend/src/personnel/ro/personnel.ro.ts
frontend/src/common/enums/index.ts
frontend/src/common/enums/role.enum.ts
frontend/src/common/enums/status.enum.ts
frontend/src/components/header/Header.tsx
frontend/src/components/layout/Layout.tsx
frontend/src/components/table/Table.tsx
frontend/src/components/table/interface.ts
frontend/src/components/table/utils.ts
frontend/src/components/toggle/Toggle.tsx
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/routes/PrivateRoute.tsx
keycloak/default.json

[TC-0279](https://bcdevex.atlassian.net/browse/TC-0279)
Objective:
- Use class validator to omit certain personnel fields if the user role is logistics (vs coordinator)

[TC-279] BE changes for role permissions

---

.gitignore
DEV.md
notebooks/members.ipynb
notebooks/package-lock.json
notebooks/package.json

[TC-122](https://bcdevex.atlassian.net/browse/TC-122)
Objective:
This is not final until we get the updated final list of members.
[TC-122]: https://bcdevex.atlassian.net/browse/TC-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-122] initial script for migrating data

---

backend/src/auth/roles.guard.ts
frontend/src/components/ui/Error.tsx
frontend/src/components/ui/index.ts
frontend/src/hooks/index.ts
frontend/src/hooks/useError.tsx
frontend/src/hooks/useTable.tsx
frontend/src/providers/Auth.tsx
frontend/src/providers/Error.tsx
frontend/src/providers/index.ts
frontend/src/routes/AppRoutes.tsx

Objective:
- error component
- using lazy loading in app routes (so we shouldn't have to set a loading view conditionally in each component)

[CHORE]: added error component and updated App Routes

---

frontend/src/pages/dashboard/Dashboard.tsx

Objective:
- table header label

[FIX] table header label fix

---

Makefile
backend/src/database/entities/form.entity.ts
backend/src/form/form.controller.ts
backend/src/form/form.module.ts
backend/src/form/form.service.ts

[CHORE] saving formId and submissionId

---

frontend/src/components/table/Table.tsx
frontend/src/components/table/body/TableBodyRow.tsx
frontend/src/components/table/interface.ts
frontend/src/components/ui/Status.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/pages/profile/ProfileHeader.tsx

[CHORE] prettier

---

backend/package-lock.json
backend/package.json
backend/src/common/enums/availability-type.enum.ts
backend/src/common/utils.ts
backend/src/database/entities/availability.entity.ts
backend/src/database/entities/personnel.entity.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/dto/get-availability.dto.ts
backend/src/personnel/dto/get-personnel.dto.ts
backend/src/personnel/dto/update-availability.dto.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.module.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/availability.ro.ts
backend/src/personnel/ro/personnel.ro.ts

[TC-0259](https://bcdevex.atlassian.net/browse/TC-0259)
Objective:
- Be endpoints scheduler/availability filter

[TC-0259] BE scheduler endpoints

---

backend/src/personnel/personnel.service.ts

[FIX] Dates 

---

frontend/src/common/enums/availability-type.enum.ts
frontend/src/components/ui/MonthPicker.tsx
frontend/src/hooks/usePersonnel.tsx
frontend/src/pages/dashboard/constants.ts
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/Scheduler.tsx
frontend/src/pages/profile/SchedulerControl.tsx
frontend/src/pages/profile/SchedulerHeader.tsx
frontend/src/pages/profile/SchedulerRow.tsx
frontend/src/utils/classes.ts
frontend/src/utils/index.ts
frontend/tailwind.config.cjs

[TC-258](https://bcdevex.atlassian.net/browse/TC-258)
Objective:
[TC-258]: https://bcdevex.atlassian.net/browse/TC-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-258] Scheduler + Integration

---

frontend/src/routes/index.ts
openshift/client.dc.yml
openshift/server.dc.yml

[FIX] Fix link import + resource limits

---

backend/src/personnel/personnel.service.ts

Objective:
- Bugfix - count was off for default page load on dashboard

[FIX] default result for dashboard page

---

backend/src/common/utils.ts
backend/src/database/entities/personnel.entity.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.service.ts

[TC-0237](https://bcdevex.atlassian.net/browse/TC-0237)
Objective:

[TC-237] Backend changes

---

backend/src/common/utils.ts
backend/src/database/entities/personnel-function-experience.entity.ts
backend/src/database/entities/personnel.entity.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.service.ts
frontend/src/common/enums/button-type.enum.ts
frontend/src/common/types.ts
frontend/src/components/header/Header.tsx
frontend/src/components/header/UserMenu.tsx
frontend/src/components/search/Search.tsx
frontend/src/components/ui/Button.tsx
frontend/src/components/ui/Divider.tsx
frontend/src/components/ui/SectionHeader.tsx
frontend/src/components/ui/index.ts
frontend/src/hooks/helpers.ts
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx
frontend/src/pages/profile/DetailsSection.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileHeader.tsx
frontend/src/pages/splash/SplashMain.tsx
frontend/src/styles/typography.css

Objective:
- matched profile to new design changes
- profile/header responsiveness

[CHORE] profile UI update/responsiveness

---

backend/src/database/entities/personnel.entity.ts
backend/src/personnel/personnel.controller.ts
frontend/package-lock.json
frontend/package.json
frontend/src/common/types.ts
frontend/src/components/filters/classes.ts
frontend/src/components/header/Header.tsx
frontend/src/components/table/Table.tsx
frontend/src/components/toggle/Toggle.tsx
frontend/src/components/ui/Button.tsx
frontend/src/components/ui/classes.ts
frontend/src/components/ui/index.ts
frontend/src/components/ui/inputs/Select.tsx
frontend/src/components/ui/inputs/TextArea.tsx
frontend/src/components/ui/inputs/TextInput.tsx
frontend/src/components/ui/inputs/helpers.ts
frontend/src/components/ui/inputs/index.ts
frontend/src/components/ui/inputs/types.ts
frontend/src/hooks/index.ts
frontend/src/hooks/usePersonnel.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx
frontend/src/pages/dashboard/constants.ts
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileEditForm.tsx
frontend/src/pages/profile/ProfileEditPopup.tsx
frontend/src/pages/profile/constants.ts

[TC-0273](https://bcdevex.atlassian.net/browse/TC-0273)
Objective:
- Edit profile pop up form 
- field validation
*note: we may want to look at the field validation/dto's for creating/updating personnel a bit more closely. ie: shoudl we disable the email edit field if this is going to be a unique field in order to prevent duplicate form submissions from CHEFS

[TC-273] FE changes

---

backend/src/common/utils.ts
backend/src/database/entities/personnel.entity.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/personnel.service.ts
frontend/src/common/links.ts
frontend/src/hooks/usePersonnel.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/profile/ProfileEditForm.tsx
frontend/src/pages/profile/constants.ts

Objective:
- util script not running for data seed on dev
- reduced the num of resources created from 500 to 200

[FIX] seed script, validation, initial query 

---

frontend/src/components/table/classes.ts
frontend/src/hooks/helpers.ts

[FIX] Availability type

---

backend/src/common/enums/classification.enum.ts
frontend/src/common/enums/classification.enum.ts
frontend/src/components/table/classes.ts

[TC-352](https://bcdevex.atlassian.net/browse/TC-352)
Objective:
- remove BCNU
[TC-352]: https://bcdevex.atlassian.net/browse/TC-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-352] remove BCNU

---

backend/src/app.controller.ts
backend/src/common/utils.ts
backend/src/database/entities/personnel.entity.ts
backend/src/function/function.controller.ts
backend/src/function/function.module.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/region-location/region-location.controller.ts
backend/src/region-location/region-location.module.ts
backend/src/region-location/region-location.service.ts
backend/test/app.spec.ts
frontend/src/hooks/useGetFilters.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx
frontend/src/pages/dashboard/constants.ts

Objective:
- fix the request to get dashboard filters

[FIX] dash filters data

---

backend/src/app.controller.ts
backend/src/form/form.service.ts
backend/src/logger/logger.service.ts
backend/src/main.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.module.ts
backend/src/personnel/personnel.service.ts

Objective:
- The logs during development weren't displaying with the proper controller/service
- added transient scope to logger to resolve

[FIX] logger context

---

Makefile
backend/src/database/create-availability-functions.ts
backend/src/personnel/dto/update-availability.dto.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/availability.ro.ts
frontend/src/components/filters/date-picker/DatePickerHeader.tsx
frontend/src/components/filters/date-picker/interface.ts
frontend/src/pages/dashboard/constants.ts
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/Scheduler.tsx
frontend/src/pages/profile/SchedulerPopUp.tsx
frontend/src/pages/profile/SchedulerRow.tsx
frontend/src/utils/classes.ts
frontend/src/utils/helpers.ts
frontend/src/utils/index.ts

[TC-348](https://bcdevex.atlassian.net/browse/TC-348)
Objective:
Working version of edit scheduler
Click on a cell to get it going
Backend changes to allow for pulling the right dates, and for updating so that non-selected edits are deleted
[TC-348]: https://bcdevex.atlassian.net/browse/TC-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-348] edit scheduler

---

backend/src/personnel/personnel.service.ts
frontend/src/components/filters/classes.ts
frontend/src/components/filters/date-picker/DatePicker.tsx
frontend/src/components/filters/date-picker/helpers.ts
frontend/src/components/table/body/TableBodyCell.tsx
frontend/src/components/table/classes.ts
frontend/src/components/ui/Tooltip.tsx
frontend/src/components/ui/index.ts
frontend/src/hooks/helpers.ts
frontend/src/hooks/useGetFilters.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx

[TC-0355](https://bcdevex.atlassian.net/browse/TC-0355)
Objective:
- instead of partial, show # of # days for a partial result
- return all resources on page load, include availability status if exists (for the current date) or NOT_INDICATED otherwise
- ensure page load is quick

[TC-355] Availability Filter 

---

backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.service.ts
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/SchedulerPopUp.tsx

[TC-364](https://bcdevex.atlassian.net/browse/TC-364)
[TC-368](https://bcdevex.atlassian.net/browse/TC-368)
Objective:
- Delete event by passing in NOT_INDICATED
- Change title to New or Edit depending on type of mode
- Better syncing of calendar and inputs
[TC-364]: https://bcdevex.atlassian.net/browse/TC-364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TC-368]: https://bcdevex.atlassian.net/browse/TC-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-364] delete event, "new" vs "edit" event, calendar

---

frontend/src/pages/profile/SchedulerPopUp.tsx

Objective:
New designs
Please go ahead and merge after approval

[CHORE] change wording on pop up labels to line up with new designs

---

frontend/src/providers/Auth.tsx
frontend/src/providers/Error.tsx
frontend/src/routes/AppRoutes.tsx

[TC-346](https://bcdevex.atlassian.net/browse/TC-346)
Objective:
I *think* bumping the auth component to higher up the tree helps with this issue. I tried deploying on Dev and Qudsia seemed to be able to access properly.
I am introducing a bit of tech debt here though to handle this error better.
[TC-346]: https://bcdevex.atlassian.net/browse/TC-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-346] bump auth up to the first component in tree

---

backend/src/database/seed-functions.ts

[FIX] seed function: update functions list for db

---

frontend/src/components/filters/classes.ts
frontend/src/components/table/body/TableBodyCell.tsx
frontend/src/components/ui/Dialog.tsx
frontend/src/components/ui/index.ts
frontend/src/components/ui/inputs/TextArea.tsx
frontend/src/hooks/helpers.ts
frontend/src/hooks/useGetFilters.tsx
frontend/src/pages/dashboard/constants.ts
frontend/src/pages/profile/Detail.tsx
frontend/src/pages/profile/EditNotes.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileEditForm.tsx
frontend/src/pages/profile/ProfileNotes.tsx

[TC-0343](https://bcdevex.atlassian.net/browse/TC-0343)
Objective:
- edit notes

[TC-343] Edit Notes

---

backend/src/personnel/personnel.service.ts

[FIX] return functions with update personnel

---

DEVOPS.md
Makefile
openshift/backup.bc.yml
openshift/backup.dc.yml

[TC-123](https://bcdevex.atlassian.net/browse/TC-123)
Objective:
Creates backup resource, documentation
[TC-123]: https://bcdevex.atlassian.net/browse/TC-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-123] backups pod and documentation

---

frontend/src/components/filters/CascadingMenu.tsx
frontend/src/components/filters/MultiSelect.tsx
frontend/src/components/filters/MultiSelectGroup.tsx
frontend/src/components/filters/SingleSelect.tsx
frontend/src/components/filters/date-picker/DatePicker.tsx
frontend/src/components/filters/date-picker/DatePickerHeader.tsx
frontend/src/components/filters/date-picker/ResetButton.tsx
frontend/src/components/filters/date-picker/interface.ts
frontend/src/components/ui/Chip.tsx
frontend/src/components/ui/MenuChips.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx

[TC-0371](https://bcdevex.atlassian.net/browse/TC-0371)
Objective:
- reset date range clearing availability type 
- clearing availability type resets date range

[TC-371] reset date range

---

frontend/src/common/links.ts
frontend/src/components/header/Header.tsx

[TC-0333](https://bcdevex.atlassian.net/browse/TC-0333)
Objective:
- redirect to intranet when clicking logo or home

[TC-333]: home redirects to intranet

---

backend/src/database/entities/personnel.entity.ts
backend/src/personnel/dto/create-personnel.dto.ts
frontend/src/components/filters/classes.ts
frontend/src/components/ui/inputs/Select.tsx
frontend/src/components/ui/inputs/TextArea.tsx
frontend/src/components/ui/inputs/TextInput.tsx
frontend/src/components/ui/inputs/types.ts
frontend/src/hooks/usePersonnel.tsx
frontend/src/pages/profile/EditNotes.tsx
frontend/src/pages/profile/ProfileEditForm.tsx
frontend/src/pages/profile/ProfileNotes.tsx
frontend/src/pages/profile/constants.ts
frontend/tailwind.config.cjs

[TC-0362](https://bcdevex.atlassian.net/browse/TC-0362)
Objective:
- field validation errors

[TC-362]: Field validation errors

---

backend/src/common/enums/status.enum.ts
backend/src/common/utils.ts
backend/src/database/entities/personnel.entity.ts
backend/src/personnel/personnel.service.ts
frontend/src/common/enums/status.enum.ts
frontend/src/components/ui/Banner.tsx
frontend/src/components/ui/Dialog.tsx
frontend/src/components/ui/Status.tsx
frontend/src/components/ui/inputs/Select.tsx
frontend/src/components/ui/inputs/TextArea.tsx
frontend/src/components/ui/inputs/TextInput.tsx
frontend/src/pages/ReviewApplicant.tsx
frontend/src/pages/profile/EditNotes.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileHeader.tsx

[TC-0356](https://bcdevex.atlassian.net/browse/TC-0356)
Objective:
- Add banner for Pending Approval status 
- Add button to approve
- Add confirmation pop up
- Add active/inactive toggle

[TC-356]: Active toggle and Pending applicant banner

---

frontend/src/components/ui/Banner.tsx
frontend/src/pages/profile/EditNotes.tsx

[TC-0342](https://bcdevex.atlassian.net/browse/TC-0342)
Objective:
- Fix the spacing for the notes edit view

[TC-343] fix edit notes view

---

backend/src/personnel/personnel.controller.ts

[TC-0381](https://bcdevex.atlassian.net/browse/TC-0381)
Objective:
- bugfix for logistics to edit profile

[TC-381] add logistic role to update endpoint

---

frontend/src/pages/splash/SplashMain.tsx
frontend/src/pages/splash/constants.ts

[TC-0330](https://bcdevex.atlassian.net/browse/TC-0330)
Objective:
- remove unused splash links

[TC-330] remove splash links

---

backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/dto/personnel-experiences.dto.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.module.ts
backend/src/personnel/personnel.service.ts
frontend/src/hooks/usePersonnel.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileEditForm.tsx
frontend/src/pages/profile/ProfileFunctionEdit.tsx
frontend/src/pages/profile/ProfileFunctions.tsx

[TC-309](https://bcdevex.atlassian.net/browse/TC-309)
[TC-310](https://bcdevex.atlassian.net/browse/TC-310)
Objective:
FE + BE Edit Experience
[Prototype Here](https://www.figma.com/proto/EsuYOEyGPvIVDEFGnYCJ2f/CoCo-EMCR%3A-TEAMS-Redesign?page-id=2349%3A12933&type=design&node-id=2412-74390&viewport=-237%2C-1598%2C0.2&t=kxYM1ZJE08ZzOdWh-1&scaling=scale-down&starting-point-node-id=2358%3A47218)
[TC-309]: https://bcdevex.atlassian.net/browse/TC-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TC-310]: https://bcdevex.atlassian.net/browse/TC-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-309] BE + FE update Experiences

---

frontend/vite.config.ts

[FIX] fix assets

---

backend/src/common/enums/index.ts
backend/src/common/enums/union-membership.enum.ts
backend/src/common/utils.ts
backend/src/database/entities/personnel.entity.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/ro/personnel.ro.ts
frontend/src/common/enums/index.ts
frontend/src/common/enums/union-membership.enum.ts
frontend/src/components/table/classes.ts
frontend/src/hooks/helpers.ts
frontend/src/pages/dashboard/constants.ts
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileEditForm.tsx
frontend/src/pages/profile/constants.ts
notebooks/members.ipynb

Objective:
- rename to avoid confusion

[CHORE] rename classification to union membership

---

frontend/src/components/filters/CascadingMenu.tsx
frontend/src/components/filters/MultiSelect.tsx
frontend/src/components/filters/MultiSelectGroup.tsx
frontend/src/components/filters/NestedMenu.tsx
frontend/src/components/filters/SingleSelect.tsx
frontend/src/components/filters/classes.ts
frontend/src/components/filters/date-picker/DatePickerHeader.tsx
frontend/src/components/filters/date-picker/MonthSelector.tsx
frontend/src/components/filters/date-picker/YearSelector.tsx
frontend/src/components/search/Search.tsx
frontend/src/components/ui/Chip.tsx
frontend/src/components/ui/MenuButton.tsx
frontend/src/components/ui/MenuChips.tsx
frontend/src/components/ui/MonthPicker.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx
frontend/src/styles/typography.css
frontend/tailwind.config.cjs

[TC-0222](https://bcdevex.atlassian.net/browse/TC-0222)
Objective:
- Clear search
- clear all

[TC-222]: Clear search, Clear all

---

frontend/src/components/ui/Banner.tsx
frontend/src/pages/dashboard/constants.ts
frontend/src/pages/profile/ProfileHeader.tsx

Objective:
- Banner squished
- Num days deployed now using difference in days vs difference in calendar days

[FIX]: Banner layout

---

backend/src/database/entities/personnel.entity.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/personnel.module.ts
frontend/src/common/links.ts
frontend/src/components/header/Header.tsx
frontend/src/components/ui/Dialog.tsx
frontend/src/components/ui/Status.tsx
frontend/src/components/ui/inputs/TextArea.tsx
frontend/src/components/ui/inputs/types.ts

[FIX] prettier/lint

---

frontend/src/components/ui/Banner.tsx
frontend/src/pages/splash/SplashMain.tsx
frontend/src/pages/splash/constants.ts

[TC-0320](https://bcdevex.atlassian.net/browse/TC-0320)
Objective:

[TC-320] removed unused link

---

frontend/src/pages/profile/ProfileFunctions.tsx

[TC-0400](https://bcdevex.atlassian.net/browse/TC-0400)
Objective:

[TC-400] wording on function/experienced

---

openshift/backup.dc.yml
openshift/client.dc.yml
openshift/patroni.dc.yml
openshift/server.dc.yml
openshift/sysdig.yml

[TC-336](https://bcdevex.atlassian.net/browse/TC-336)
Objective:
[TC-336]: https://bcdevex.atlassian.net/browse/TC-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-336] adjust resource requests + limits

---

frontend/src/components/ui/inputs/helpers.ts
frontend/src/pages/profile/constants.ts

Objective:
- I think I got it this time

[FIX] Phone number formatting + validation

---

.github/workflows/ci-deploy.yaml
.github/workflows/ci-migrations-dev.yaml
.github/workflows/ci-migrations-test.yaml
.github/workflows/ci-seed-dummy-data.yml
Makefile
frontend/src/hooks/useAvailability.tsx

Objective:
- run build only if there are changes
- updated name of migrations action
- created action for migrations on test

[CHORE] run actions conditionally

---

frontend/src/pages/profile/ProfileHeader.tsx

[TC-0403](https://bcdevex.atlassian.net/browse/TC-0403)
Objective:
- Showing "currently deployed" instead of "Last deployment 0 days ago" if currently deployed

[TC-403] updated last deployed

---

.github/workflows/ci-deploy.yaml

[FIX] fix workflow

---

.github/workflows/ci-promote-test.yaml

[FIX] test deploy fix

---

openshift/backup.dc.yml
openshift/client.dc.yml
openshift/patroni.dc.yml

[TC-336](https://bcdevex.atlassian.net/browse/TC-336)
Objective:
[TC-336]: https://bcdevex.atlassian.net/browse/TC-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-336] resources at a good balance, higher PVC size

---

.github/workflows/ci-deploy.yaml

Objective:
- remove conditional build

[FIX] remove conditional builds from GHA

---

.github/workflows/ci-promote.prod.yaml
Makefile
openshift/backup.dc.yml
openshift/server.dc.yml

Objective:
Get prod promotion process going. The dcs are already up on the prod environment, the environment is up and requires (currently) my approval.

[CHORE] prod promotion GHA

---

Makefile

[CHORE] fix tag prod

---

DEV.md
frontend/.dockerignore
frontend/.gitignore
frontend/src/components/filters/classes.ts
frontend/src/components/filters/date-picker/DatePicker.tsx
frontend/src/components/filters/date-picker/MonthSelector.tsx
frontend/src/components/filters/date-picker/YearSelector.tsx
frontend/src/components/header/Header.tsx
frontend/src/components/header/UserMenu.tsx
frontend/src/components/search/Search.tsx
frontend/src/components/table/Table.tsx
frontend/src/components/table/body/TableBodyCell.tsx
frontend/src/components/table/classes.ts
frontend/src/components/toggle/Toggle.tsx
frontend/src/components/ui/Banner.tsx
frontend/src/components/ui/Dialog.tsx
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/pages/profile/Detail.tsx
frontend/src/pages/profile/DetailsSection.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileFunctions.tsx
frontend/src/pages/profile/ProfileHeader.tsx
frontend/src/pages/profile/ProfileNotes.tsx
frontend/src/pages/profile/SchedulerControl.tsx
frontend/src/pages/profile/SchedulerHeader.tsx
frontend/src/pages/profile/SchedulerRow.tsx
frontend/src/styles/typography.css
frontend/src/utils/classes.ts
frontend/tailwind.config.cjs
frontend/vite.config.ts

Objective:
- improve light accessibility scores
- (note: performance is decreased due to local env) 
-

[FIX] accessibility score

---

frontend/src/components/ui/inputs/TextInput.tsx
frontend/src/components/ui/inputs/types.ts
frontend/src/pages/profile/ProfileEditForm.tsx
frontend/src/pages/profile/constants.ts

[TC-402](https://bcdevex.atlassian.net/browse/TC-402)
Objective:
-  set autocomplete off on edit form
- expand size of email input
[TC-402]: https://bcdevex.atlassian.net/browse/TC-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-402]: set autocomplete off on edit form

---

frontend/vite.config.ts

Objective:
- too slow on local so I've set the dev config to false

[FIX] remove vite dev config

---

frontend/src/components/table/Table.tsx
frontend/src/components/ui/Loading.tsx
frontend/src/pages/dashboard/constants.ts

[TC-0408](https://bcdevex.atlassian.net/browse/TC-0408)
Objective:

[TC-408] FIX loading component + rename work/home location

---

frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileDetails.tsx

[TC-413](https://bcdevex.atlassian.net/browse/TC-413)
Objective:
- update date joined on applicant reviewed
[TC-413]: https://bcdevex.atlassian.net/browse/TC-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-413] change datejoined on applicant reviewed

---

frontend/src/pages/profile/constants.ts

Objective:
- update the validation error for a required phone number

[FIX] phone number validation

---

backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/common/logger.config.ts
backend/src/filters/http-exception.filter.ts
backend/src/logger/logger.module.ts
frontend/src/pages/profile/SchedulerControl.tsx

[TC-124](https://bcdevex.atlassian.net/browse/TC-124)
Objective:
For now, we'll do file rotation saves. We have a separate one for logging that clears after 2 weeks and one for errors that don't, but rotates monthly. We can tweak this as we see use; if there's too much logging or what have you.
[TC-124]: https://bcdevex.atlassian.net/browse/TC-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-124] file rotation saves for info and separate for errors

---

frontend/package-lock.json
frontend/src/pages/profile/Profile.tsx

[FIX] import

---

backend/package-lock.json
backend/package.json
backend/src/common/logger.config.ts
backend/src/logger/logger.module.ts

[CHORE] Remove daily rotate file

---

frontend/src/pages/profile/ProfileEditForm.tsx

[FIX] phone numbers can be null on edit form

---

backend/src/database/entities/personnel.entity.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/personnel.service.ts
frontend/src/components/filters/CascadingMenu.tsx
frontend/src/components/filters/SingleSelect.tsx
frontend/src/components/filters/classes.ts
frontend/src/components/ui/inputs/Select.tsx
frontend/src/components/ui/inputs/TextInput.tsx
frontend/src/pages/dashboard/constants.ts
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileEditForm.tsx
frontend/src/pages/profile/ProfileHeader.tsx
frontend/src/pages/profile/constants.ts
frontend/src/utils/helpers.ts

[FIX] date pst and missing location display

---

frontend/src/components/filters/date-picker/DatePicker.tsx
frontend/src/components/filters/date-picker/DatePickerHeader.tsx
frontend/src/components/filters/date-picker/interface.ts
frontend/src/pages/profile/SchedulerPopUp.tsx

[TC-430](https://bcdevex.atlassian.net/browse/TC-430)
Objective:
[TC-430]: https://bcdevex.atlassian.net/browse/TC-430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-430] scheduler no longer changing months to starting month

---

backend/src/form/form.service.ts
backend/src/form/interface.ts

[FIX] fix remote only

---

frontend/src/pages/profile/SchedulerPopUp.tsx

[TC-433](https://bcdevex.atlassian.net/browse/TC-433)
Objective:
[TC-433]: https://bcdevex.atlassian.net/browse/TC-433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-433] single dates now has toDay for scheduler

---

backend/src/database/migrations/1711575873472-datetype.ts
backend/src/database/migrations/1711575873472-migration.ts
frontend/src/utils/helpers.ts

[TC-416](https://bcdevex.atlassian.net/browse/TC-416)
Objective:
- displaying proper date based on users timezone
[TC-416]: https://bcdevex.atlassian.net/browse/TC-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-416] Date joined and application date showing correct date based on timezone

---

frontend/src/pages/profile/SchedulerPopUp.tsx

[TC-401](https://bcdevex.atlassian.net/browse/TC-401)
Objective:

[TC-401] confirm modal for edit/delete avail

---

frontend/src/pages/profile/Profile.tsx

[TC-427](https://bcdevex.atlassian.net/browse/TC-427)
Objective:
[TC-427]: https://bcdevex.atlassian.net/browse/TC-427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-427] change to add avail

---

backend/src/common/const.ts
backend/src/database/entities/personnel.entity.ts
backend/src/database/migrations/1712342286284-ics-and-supervisor-migration.ts
backend/src/database/seed-trainings.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.module.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/personnel.ro.ts
frontend/src/hooks/helpers.ts
frontend/src/pages/dashboard/constants.ts

[TC-458](https://bcdevex.atlassian.net/browse/TC-458)
Objective:
Migration for Approved by Supervisor
Seeding functions for Trainings
Returning both values to the frontend
[TC-458]: https://bcdevex.atlassian.net/browse/TC-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-458] add ICS training for the backend

---

backend/src/database/entities/personnel.entity.ts
backend/src/personnel/dto/create-personnel.dto.ts
frontend/src/components/table/interface.ts
frontend/src/components/ui/Banner.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/constants.ts
frontend/src/pages/profile/Detail.tsx
frontend/src/pages/profile/DetailsSection.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileEditForm.tsx
frontend/src/pages/profile/ProfileHeader.tsx
frontend/src/pages/profile/constants.ts

[TC-457](https://bcdevex.atlassian.net/browse/TC-457)
Objective:
Add required fields to header and indicators of if they have been filled
Complete review contingent on both of them being TRUE
[TC-457]: https://bcdevex.atlassian.net/browse/TC-457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-457] profile header

---

Makefile

[CHORE] makefile for trainings

---

backend/src/common/utils.ts
frontend/src/components/filters/classes.ts
frontend/src/components/table/interface.ts
frontend/src/components/ui/Tabs.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/constants.ts
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileFunctions.tsx
frontend/src/pages/profile/SchedulerPopUp.tsx
frontend/tailwind.config.cjs

[TC-0490](https://bcdevex.atlassian.net/browse/TC-0490)
Objective:
- fix bug caused by tailwind config colours update
- fixed error from using Date | string on personnel interface
- fixed local seed script

[TC-490] colours

---

frontend/src/hooks/useAxios.tsx
frontend/src/hooks/useFunctions.tsx
frontend/src/hooks/useGetFilters.tsx
frontend/src/hooks/usePersonnel.tsx
frontend/src/hooks/useTable.tsx
frontend/src/providers/Role.tsx

Objective:
- added dependencies to useEffect hooks

[CHORE] added required dependencies to useEffect hooks

---

backend/src/common/enums/ministry.enum.ts
backend/src/database/migrations/1714002300892-ministry-enum.ts
backend/src/database/migrations/1714002327425-ministry-enum-two.ts

[FIX]: change ministry enum to MMHA from MHA

---

frontend/src/components/table/footer/TableFooterPageSelect.tsx
frontend/src/components/ui/Table.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/Dashboard.tsx

[TC-0519](https://bcdevex.atlassian.net/browse/TC-0519)
Objective:
- Bug found by QA during pre-release regression testing on pagination when selecting number of results from the drop down on the footer
- Reseting to first page when changing number of results to show per page.

[TC-519]: fix pagination

---

frontend/src/pages/profile/ProfileEditForm.tsx

Objective:
- removed the application date from being updated with the profile edit updates

[FIX] profile update application date

---

frontend/src/pages/dashboard/Dashboard.tsx

Objective:
- logistics view for pagination fix

[FIX] logistics view pagination

---

backend/src/personnel/personnel.service.ts

We should get this deployed to dev/test

[CHORE] endpoint change bcws

---

Makefile
backend/src/swagger.ts
openshift/server.dc.yml
openshift/server.prep.yml

Objective:
- added token to oc

[CHORE] added token secret to openshift

---

backend/src/personnel/personnel.controller.ts
frontend/src/pages/profile/SchedulerPopUp.tsx

[TC-491](https://bcdevex.atlassian.net/browse/TC-491)
Objective:
Edit event block without deleting it always
Confirm popup only on delete and when events are being deleted
Correct dates for events that go beyond the month
[TC-491]: https://bcdevex.atlassian.net/browse/TC-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-491 Edit event doesn't always delete

---

backend/src/database/migrations/1714754205889-bcws-migration.ts
backend/src/form/form.controller.ts
backend/src/form/form.service.ts

Objective:
- drop non null on region

[FIX] drop non null on region

---

backend/src/personnel/personnel.service.ts

Objective:
- update emcr personnel fix

[FIX] emcr personnel update 

---

Makefile
backend/src/database/migrations/1714757318390-insert-emcr-migration.ts

[FIX] fix order of migrations for insert

---

backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.service.ts

[TC-501](https://bcdevex.atlassian.net/browse/TC-501)
Objective:
BCWS Approved endpoint now pulling from database
[TC-501]: https://bcdevex.atlassian.net/browse/TC-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-501] working endpoint for BCWS

---

backend/src/personnel/personnel.controller.ts
frontend/cypress/e2e/coordinator.cy.ts
frontend/src/components/header/Header.tsx
frontend/src/components/layout/Layout.tsx
frontend/src/components/table/body/TableBodyCell.tsx
frontend/src/components/ui/inputs/Select.tsx
frontend/src/hooks/helpers.ts
frontend/src/hooks/usePersonnel.tsx
frontend/src/hooks/useRole.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/providers/Role.tsx

[TC-0529](https://bcdevex.atlassian.net/browse/TC-0529)
Objective:
- frontend admin toggle

[TC-529] FE routes

---

DEVOPS.md

[TC-448](https://bcdevex.atlassian.net/browse/TC-448)
Objective:
- versioning steps added to readme
[TC-448]: https://bcdevex.atlassian.net/browse/TC-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-448] readme added versioning instructions

---

.github/workflows/ci-bcws-faker-dev.yml
.github/workflows/ci-bcws-faker-test.yml
.github/workflows/ci-emcr-faker-dev.yml
.github/workflows/ci-emcr-faker-test.yml
.github/workflows/ci-seed-dev.yml
.github/workflows/ci-seed-prod.yml
.github/workflows/ci-seed-test.yml
.github/workflows/ci-tests.yaml
Makefile
backend/src/common/bcws-seed.ts
backend/src/common/emcr-seed.ts
backend/src/database/entities/bcws/bcws-personnel-language.entity.ts
backend/src/database/entities/bcws/bcws-personnel.entity.ts
backend/src/database/migrations/1715887048702-language-id-migration.ts
backend/src/database/seed-fake-bcws.ts
backend/src/database/seed-fake-emcr.ts
backend/src/database/seed.ts
backend/src/personnel/dto/emcr/create-emcr-personnel.dto.ts
backend/src/personnel/personnel.controller.ts

[FIX] fixed seed cmd bcws

---

Makefile
backend/src/database/seed.ts

[FIX] Fix seed 2

---

frontend/src/components/table/body/TableBodyCell.tsx
frontend/src/components/table/classes.ts
frontend/src/components/table/interface.ts
frontend/src/components/ui/Table.tsx
frontend/src/hooks/helpers.ts
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx
frontend/src/pages/dashboard/columns.ts

Objective:
- table state changes happen more synchronously
- removed dynamic column

[CHORE] table UI

---

backend/src/common/emcr-seed.ts
frontend/src/components/table/footer/TableFooterNav.tsx
frontend/src/components/table/footer/TableFooterPageSelect.tsx
frontend/src/components/table/interface.ts
frontend/src/components/ui/Table.tsx
frontend/src/hooks/usePagination.tsx

Objective:
- UI for pagination (fixed the truncated paginated UI on footer)

[FIX] Pagination 

---

backend/src/auth/roles.guard.ts
backend/src/auth/token.decorator.ts
backend/src/form/form.controller.ts
backend/src/personnel/personnel.controller.ts
frontend/src/hooks/usePersonnel.tsx

Objective:
- updated endpoints

[FIX] updated endpoints

---

backend/src/common/enums/bcws/skills-certifications.enum.ts
backend/src/database/entities/bcws/bcws-personnel-certification.entity.ts
backend/src/database/entities/bcws/bcws-personnel-tools.entity.ts
backend/src/database/entities/bcws/bcws-personnel.entity.ts
backend/src/personnel/dto/bcws/create-bcws-personnel-languages.dto.ts
backend/src/personnel/dto/bcws/create-bcws-personnel.dto.ts
backend/src/personnel/dto/bcws/update-bcws-personnel-certifications.dto.ts
backend/src/personnel/dto/bcws/update-bcws-personnel-tools.dto.ts
backend/src/personnel/personnel.module.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/bcws/bcws-personnel-tools.ro.ts
backend/src/personnel/ro/bcws/tools.ro.ts
frontend/src/common/enums/tools.enum.ts
frontend/src/components/ui/Accordion.tsx
frontend/src/components/ui/Dialog.tsx
frontend/src/hooks/profileData.tsx
frontend/src/hooks/usePersonnel.tsx
frontend/src/pages/dashboard/constants.ts
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileEditListSection.tsx
frontend/src/pages/profile/ProfileEditSkills.tsx
frontend/src/pages/profile/SkillsAndCertifications.tsx

[TC-579](https://bcdevex.atlassian.net/browse/TC-579)
Objective:
Edit skills, certs, languages
[TC-579]: https://bcdevex.atlassian.net/browse/TC-579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-579] edit skills

---

backend/src/form/interface.ts
frontend/src/components/ui/Table.tsx
frontend/src/components/ui/helpers.tsx
frontend/src/hooks/profileData.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/pages/profile/ProfileDetails.tsx

[TC-596](https://bcdevex.atlassian.net/browse/TC-596)
Objective:
- wording changes
- table loading... 🤞🏻
- deployed to dev in order to compare with test env
[TC-596]: https://bcdevex.atlassian.net/browse/TC-596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-596] bugfix(s)

---

backend/src/database/entities/bcws/bcws-personnel-roles.entity.ts
backend/src/database/entities/bcws/bcws-role.entity.ts
backend/src/function/function.controller.ts
backend/src/function/function.service.ts
backend/src/function/ro/role.ro.ts
backend/src/personnel/dto/bcws/create-bcws-personnel.dto.ts
frontend/src/common/enums/sections.enum.ts
frontend/src/hooks/useFunctions.tsx
frontend/src/pages/dashboard/constants.ts
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileEditListSection.tsx
frontend/src/pages/profile/ProfileEditRoles.tsx
frontend/src/pages/profile/SectionsAndRoles.tsx

[TC-580](https://bcdevex.atlassian.net/browse/TC-580)
Objective:
Edit Roles and section
Get all roles from functions controller
[TC-580]: https://bcdevex.atlassian.net/browse/TC-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-580] edit roles

---

frontend/src/components/table/body/TableBodyCell.tsx
frontend/src/components/ui/Banner.tsx
frontend/src/components/ui/Status.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileHeader.tsx

Objective:
- icons on dash
- profile header UI

[FIX] Icons/Profile UI

---

backend/src/database/migrations/1717030564509-migration.ts
backend/src/personnel/personnel.service.ts
frontend/src/components/filters/CascadingMenu.tsx
frontend/src/components/filters/MultiSelect.tsx
frontend/src/components/filters/MultiSelectGroup.tsx
frontend/src/components/filters/NestedMenu.tsx
frontend/src/hooks/helpers.ts
frontend/src/hooks/useFilters.tsx
frontend/src/hooks/useGetFilters.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx

[FIX] filters

---

backend/src/database/entities/emcr/emcr-personnel.entity.ts
backend/src/personnel/dto/emcr/create-emcr-personnel.dto.ts
backend/src/personnel/personnel.controller.ts

[TC-600](https://bcdevex.atlassian.net/browse/TC-600)
Objective:
[TC-600]: https://bcdevex.atlassian.net/browse/TC-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-600] account for string in boolean value for ICS

---

backend/src/app.controller.ts
frontend/src/pages/splash/SplashBanner.tsx
frontend/src/pages/splash/SplashMain.tsx
frontend/src/pages/splash/constants.ts
openshift/server.prep.yml

[TC-0535](https://bcdevex.atlassian.net/browse/TC-0535)
Objective:
- updated copy and adjusted padding on splash page
- added back ability to enable form and change form id using env vars

[TC-535] Splash Page

---

frontend/src/components/header/Header.tsx
frontend/src/components/ui/Accordion.tsx
frontend/src/components/ui/Banner.tsx
frontend/src/pages/ReviewApplicant.tsx
frontend/src/pages/profile/DetailsSection.tsx
frontend/src/pages/profile/NewApplicantBanner.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileFunctions.tsx
frontend/src/pages/profile/ProfileNotes.tsx
frontend/src/pages/profile/Scheduler.tsx

[TC-597](https://bcdevex.atlassian.net/browse/TC-0597)
Objective:
- bugfix for bold font on banner
- slightly adjusted padding around banner and profile on diff screen sizes
[TC-597]: https://bcdevex.atlassian.net/browse/TC-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-597] minor padding adjustments and fix font-weight

---

frontend/src/components/ui/form/FormField.tsx
frontend/src/pages/profile/ProfileEditForm/types.ts

[TC-0608](https://bcdevex.atlassian.net/browse/TC-0608)
Objective:
- driver license dropdown fix

[TC-608] fix profile edit dropdown for driver license

---

frontend/vite.config.ts

[FIX] refresh error on profile

---

frontend/src/components/header/Header.tsx

[TC-0610](https://bcdevex.atlassian.net/browse/TC-0610)
Objective:
- reload page on clicking "CORE TEAM"

[TC-610] reload page on click CORE TEAM

---

frontend/src/pages/profile/NewApplicantBanner.tsx

[TC-0495](https://bcdevex.atlassian.net/browse/TC-0495)
Objective:
- lower case word "review"

[TC-495] lower case word "review"

---

frontend/src/components/table/body/TableBodyCell.tsx
frontend/src/hooks/profileData.tsx

[TC-0621](https://bcdevex.atlassian.net/browse/TC-0621)
Objective:
- sp of "receieved"

[TC-621] spelling fix

---

backend/src/database/entities/personnel.entity.ts
frontend/src/hooks/profileData.tsx
frontend/src/pages/profile/SkillsAndCertifications.tsx

[TC-0619](https://bcdevex.atlassian.net/browse/TC-0619)
Objective:
- showing 'Not Listed' for null values on profile

[TC-619] showing 'Not Listed' for null values on profile

---

frontend/src/pages/profile/ProfileEditRoles.tsx
frontend/src/pages/profile/SectionsAndRoles.tsx

[TC-602](https://bcdevex.atlassian.net/browse/TC-602)
Objective:
[TC-602]: https://bcdevex.atlassian.net/browse/TC-602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-602] show choice

---

backend/src/auth/auth.guard.ts
backend/src/auth/roles.guard.ts
backend/src/common/bcws-seed.ts
backend/src/common/emcr-seed.ts
backend/src/database/entities/bcws/bcws-personnel.entity.ts
backend/src/database/entities/emcr/emcr-personnel.entity.ts
backend/src/form/form.service.ts
backend/src/function/function.controller.ts
backend/src/personnel/dto/bcws/create-bcws-personnel.dto.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.module.ts
backend/src/personnel/personnel.service.ts
frontend/src/components/filters/MultiSelectGroup.tsx
frontend/src/components/header/Header.tsx
frontend/src/hooks/useAxios.tsx
frontend/src/hooks/useFunctions.tsx
frontend/src/hooks/useGetFilters.tsx
frontend/src/hooks/usePersonnel.tsx
frontend/src/hooks/useRole.tsx
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileEditForm/ProfileEditForm.tsx
frontend/src/pages/profile/ProfileNotes.tsx
frontend/src/pages/profile/types.ts
frontend/src/providers/Role.tsx
keycloak/default.json

[FIX] hotfix for prod

---

backend/src/database/migrations/1717606123810-insert-location-migration.ts
backend/src/database/queries.ts

[TC-0560](https://bcdevex.atlassian.net/browse/TC-0560)
Objective:
- new locations

[TC-560] added new locations

---

backend/src/function/function.service.ts
backend/src/personnel/ro/bcws/roles-data.ro.ts
frontend/src/hooks/profileData.tsx
frontend/src/hooks/useGetFilters.tsx

Objective:
- split ministry/division on profile
- split emergency contact first/last name
- fixed list of roles on dash

[FIX] split div and min

---

backend/src/form/form.controller.ts
backend/src/form/form.service.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/personnel.service.ts

Objective:
- logging the form
- saving personnel id with form

[CHORE] form logging

---

frontend/src/components/ui/Table.tsx
frontend/src/hooks/helpers.ts
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/pages/dashboard/columns.ts

[TC-0607](https://bcdevex.atlassian.net/browse/TC-0607)
Objective:
- removed willingness/respectful workplace columns from BCWS pending table
- added in Date Applied column

[TC-607] removed unused BCWS columns

---

backend/src/common/enums/ministry.enum.ts
backend/src/database/data.ts
backend/src/database/migrations/1717694601718-agri-migration.ts
backend/src/personnel/dto/create-personnel.dto.ts
frontend/src/common/enums/ministry.enum.ts

[TC-0629](https://bcdevex.atlassian.net/browse/TC-0629)
Objective:
- removed AGRI from ministry list

[TC-629] removed AGRI from ministry list

---

backend/src/form/interface.ts

[TC-0630](https://bcdevex.atlassian.net/browse/TC-0630)
Objective:
- languages optional on form submission

[TC-630] make languages optional for form submission

---

backend/src/form/form.service.ts
backend/src/function/function.controller.ts
backend/src/function/function.service.ts

[FIX] imports

---

backend/src/form/form.service.ts
backend/src/form/interface.ts
backend/src/function/function.service.ts
backend/src/personnel/dto/bcws/create-bcws-personnel.dto.ts

[FIX] fix second choice as optional

---

backend/src/form/form.service.ts
backend/src/form/interface.ts
backend/src/function/function.service.ts

[FIX] saving OFA and PFA

---

backend/src/form/form.service.ts

[FIX] pfa string

---

frontend/src/hooks/useFunctions.tsx

[FIX] route for getting roles

---

frontend/src/pages/Unauthorized.tsx
frontend/src/providers/Role.tsx
frontend/src/providers/index.ts
frontend/src/routes/AppRoutes.tsx
frontend/src/routes/constants.ts

[TC-0646](https://bcdevex.atlassian.net/browse/TC-0646)
Objective:

[TC-646] PT 2 navigating to unauth'd page if no program or role

---

backend/src/personnel/personnel.service.ts

[TC-0635](https://bcdevex.atlassian.net/browse/TC-0635)
Objective:
- joined trainings on emcr personnel in get emcr personnel query

[TC-635] fix ics training value on dash for pending EMCR

---

frontend/src/components/filters/MultiSelect.tsx

[TC-0627](https://bcdevex.atlassian.net/browse/TC-0627)
Objective:
- using acronym for region on chip
- (min height of table is already fixed)

[TC-627] using region acronym for chip

---

frontend/src/components/table/footer/TableFooterNav.tsx

[TC-0634](https://bcdevex.atlassian.net/browse/TC-0634)
Objective:
- navigating to last page on footer

[TC-634] fixed last page nav on footer

---

frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileFunctions.tsx

[TC-640](https://bcdevex.atlassian.net/browse/TC-640)
Objective:
[TC-640]: https://bcdevex.atlassian.net/browse/TC-640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-640] disallow editing for logistics, small refactor

---

frontend/src/providers/Role.tsx

[TC-647](https://bcdevex.atlassian.net/browse/TC-646)
Objective:
[TC-647]: https://bcdevex.atlassian.net/browse/TC-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX] redirect if there's no role

---

frontend/src/common/links.ts

[TC-0656](https://bcdevex.atlassian.net/browse/TC-0656)
Objective:
- update link

[TC-656] fix link

---

backend/src/form/form.service.ts
backend/src/form/interface.ts
backend/src/form/submission.dto.ts
backend/src/personnel/personnel.service.ts

Objective:
- reject draft form
- updated the DTO for the expected response from GET request to Chefs for form data

[FIX] reject draft form

---

backend/src/auth/auth.guard.ts
keycloak/default.json

Objective:
Use client roles instead of resource access for local

[CHORE] add client roles to local keycloak

---

backend/src/app.controller.ts
backend/src/database/entities/bcws/bcws-certifications.entity.ts
backend/src/form/form.controller.ts
backend/src/function/function.controller.ts
backend/src/function/function.module.ts
backend/src/function/function.service.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/region-location/region-location.controller.ts
frontend/src/components/filters/MultiSelect.tsx
frontend/src/components/filters/MultiSelectGroup.tsx
frontend/src/components/layout/private/Header.tsx
frontend/src/components/layout/private/Layout.tsx
frontend/src/components/table/interface.ts
frontend/src/hooks/useGetFilters.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx

[TC-0521](https://bcdevex.atlassian.net/browse/TC-0521)
Objective:
- selecting a location is now selecting a region/fire centre as well
- removed CORE Team from navbar
- linted

[TC-521] Region/fire centre/location filter

---

frontend/src/components/ui/Accordion.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/SectionsAndRoles.tsx
frontend/src/pages/profile/SkillsAndCertifications.tsx

[TC-674](https://bcdevex.atlassian.net/browse/TC-674)
Objective:
BCWS LOs can only edit availability
Minor refactor
[TC-674]: https://bcdevex.atlassian.net/browse/TC-674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-674] remove bcws logistics ability to edit sections / roles

---

backend/src/personnel/ro/bcws/bcws-personnel.ro.ts
backend/src/personnel/ro/emcr/emcr-personnel.ro.ts

[FIX] expose coordinator notes (if coordinator)

---

frontend/src/pages/profile/types.ts

Objective:
In my last PR, I missed adding this prop in tyeps

[FIX] missed prop

---

openshift/client.dc.yml

Objective:
I think the gateway timeouts have been related to reaching the memory limits

[FIX] increase client resource requests

---

openshift/client.dc.yml

CPU did not need to be increased by much, if at all.
Objective:

[FIX] lower cpu request/limits for client

---

frontend/src/hooks/profileData.tsx

[TC-641](https://bcdevex.atlassian.net/browse/TC-641)
Objective:
[TC-641]: https://bcdevex.atlassian.net/browse/TC-641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-641] add drivers license to profile

---

frontend/src/pages/profile/ProfileEditForm/constants.ts
frontend/src/pages/profile/ProfileEditForm/formConfig.tsx

[TC-657](https://bcdevex.atlassian.net/browse/TC-657)
Objective:
[TC-657]: https://bcdevex.atlassian.net/browse/TC-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-657] able to edit first and last name

---

backend/src/bcws/bcws.service.ts
backend/src/bcws/dto/get-bcws-personnel.dto.ts
frontend/src/common/enums/function.enum.ts
frontend/src/pages/dashboard/DashboardFilters.tsx

[TC-670](https://bcdevex.atlassian.net/browse/TC-670)
Objective:
[TC-670]: https://bcdevex.atlassian.net/browse/TC-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-670] BCWS Interested checkboxes

---

backend/src/common/enums/emcr/function.enum.ts
backend/src/common/enums/function.enum.ts
backend/src/database/queries.ts

[TC-659](https://bcdevex.atlassian.net/browse/TC-659)
Objective:
[TC-659]: https://bcdevex.atlassian.net/browse/TC-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-659] add response information (still need db query to be done)

---

backend/src/form/form.service.ts
backend/src/form/interface.ts

[TC-680](https://bcdevex.atlassian.net/browse/TC-680)
Objective:
[TC-680]: https://bcdevex.atlassian.net/browse/TC-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-680] accept new data type for deployment options

---

Makefile
backend/src/bcws/bcws.service.ts
backend/src/emcr/emcr.service.ts
backend/src/personnel/dto/get-personnel.dto.ts
frontend/src/hooks/useFilters.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx

[TC-730](https://bcdevex.atlassian.net/browse/TC-730)
Objective:
Dashboard includes checkbox for including travellers based on their preference
[TC-730]: https://bcdevex.atlassian.net/browse/TC-730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-730] include travellers checkbox in dashboard

---

frontend/src/common/enums/travel-preference.enum.ts

Objective:
Change `"Anywhere"` to `"Anywhere in BC"`

[FIX] willing to travel anywhere text

---

backend/src/database/entities/bcws/bcws-personnel.entity.ts

[TC-691](https://bcdevex.atlassian.net/browse/TC-691)
Objective:
[TC-691]: https://bcdevex.atlassian.net/browse/TC-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-691] new is 5 days instead of 30

---

backend/src/database/entities/emcr/emcr-personnel.entity.ts

[TC-691](https://bcdevex.atlassian.net/browse/TC-691)
Objective:
[TC-691]: https://bcdevex.atlassian.net/browse/TC-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-691] emcr to 5 days instead of 30

---

.github/workflows/ci-tests.yaml
backend/src/personnel/personnel.service.ts

[TC-689](https://bcdevex.atlassian.net/browse/TC-689)
Objective:
[TC-689]: https://bcdevex.atlassian.net/browse/TC-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-689] sort by date approved for new, then last name

---

frontend/src/pages/dashboard/constants.ts

[TC-738](https://bcdevex.atlassian.net/browse/TC-738)
Objective:
[TC-738]: https://bcdevex.atlassian.net/browse/TC-738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-738] rename travel preference column

---

backend/package-lock.json
backend/src/auth/auth.controller.ts
backend/src/auth/auth.guard.ts
backend/src/auth/auth.module.ts
backend/src/auth/auth.service.ts
backend/src/auth/interface.ts
backend/src/auth/ro/user-info.ro.ts
backend/src/database/seed-fake-emcr.ts
backend/src/filters/http-exception.filter.ts
backend/src/main.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/member-profile.ro.ts
backend/src/personnel/ro/personnel.ro.ts
frontend/cypress/e2e/coordinator.cy.ts

[TC-0763](https://bcdevex.atlassian.net/browse/TC-0763)
Objective:
- BE Changes for supervisor/member login

[TC-763] BE: Login flow

---

backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/member-profile.ro.ts
frontend/src/common/enums/index.ts
frontend/src/common/enums/tabs.enum.ts
frontend/src/components/profile/common/ProfileSectionHeader.tsx
frontend/src/components/profile/common/index.ts
frontend/src/components/profile/functions/MemberProfileFunctions.tsx
frontend/src/components/profile/functions/index.ts
frontend/src/components/profile/header/ProfileMemberHeader.tsx
frontend/src/components/profile/scheduler/MemberScheduler.tsx
frontend/src/components/profile/scheduler/MemberSchedulerControl.tsx
frontend/src/components/profile/scheduler/MemberSchedulerHeader.tsx
frontend/src/components/profile/scheduler/MemberSchedulerKey.tsx
frontend/src/components/profile/scheduler/index.ts
frontend/src/components/profile/sections-roles/MemberSectionAndRoles.tsx
frontend/src/components/profile/sections-roles/index.ts
frontend/src/components/profile/skills-certifications/MemberSkillsAndCertifications.tsx
frontend/src/components/profile/skills-certifications/index.ts
frontend/src/components/tabs/Availability.tsx
frontend/src/components/tabs/Details.tsx
frontend/src/hooks/profileData.tsx
frontend/src/hooks/useMemberProfile.tsx
frontend/src/hooks/useProgramFieldData.tsx
frontend/src/pages/profile/MemberProfile.tsx

[TC-678](https://bcdevex.atlassian.net/browse/TC-678)
Objective:
Getting the initial profile step working with some data changes
Tabs
TODOS in other tickets:
- Scheduler changes
- Edit profile changes
- Certs / Tools / Languages
[TC-678]: https://bcdevex.atlassian.net/browse/TC-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-678] starting reorg of profile page, tabs

---

backend/src/auth/auth.service.ts
backend/src/auth/interface.ts
backend/src/bcws/bcws.service.ts
backend/src/common/enums/availability-type.enum.ts
backend/src/database/entities/availability.entity.ts
backend/src/database/entities/personnel.entity.ts
backend/src/database/migrations/1732125404215-availability-type-migration.ts
backend/src/emcr/emcr.service.ts
backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/dto/get-personnel.dto.ts
backend/src/personnel/dto/update-availability.dto.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/availability.ro.ts
backend/src/personnel/ro/get-personnel.ro.ts
frontend/src/common/constants.ts
frontend/src/common/enums/availability-type.enum.ts
frontend/src/components/profile/scheduler/Scheduler.tsx
frontend/src/components/profile/scheduler/SchedulerPopUp.tsx
frontend/src/components/profile/scheduler/SchedulerRow.tsx
frontend/src/hooks/helpers.ts
frontend/src/utils/classes.ts

[TC-0807](https://bcdevex.atlassian.net/browse/TC-0807)
Objective:
- remove 'AVAILABLE' and 'NOT_INDICATED' from availability type enum
- instead use null and delete if updating from deployed/unavailable to available
- show white on member profile to indicate available and green otherwise
*note:* currently there is a bug when filtering the dash by availability. We are only returning full, not partial matched. Have left a TODO. 
[Ticket to fix filter](https://bcdevex.atlassian.net/browse/TC-821)

[TC-807] Scheduler Changes

---

backend/src/app.controller.ts
backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.ts
backend/src/auth/interface.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.service.ts
frontend/src/components/layout/private/UserMenu.tsx
frontend/src/hooks/useRecommitment.tsx
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/providers/Role.tsx
frontend/src/routes/AppRoutes.tsx
frontend/src/routes/PrivateRoute.tsx
frontend/src/routes/Redirect.tsx
frontend/src/routes/RoleProtectedRoute.tsx

[CHORE] Roles update 2

---

backend/src/bcws/ro/bcws-personnel-roles.ro.ts
backend/src/database/entities/bcws/bcws-personnel-roles.entity.ts
frontend/src/common/constants.ts
frontend/src/components/profile/common/ProfileSectionHeader.tsx
frontend/src/components/profile/sections-roles/MemberSectionAndRoles.tsx
frontend/src/components/tabs/Availability.tsx

[TC-813](https://bcdevex.atlassian.net/browse/TC-813)
Objective:
Frontend for displaying section and roles
Component should be able to handle multiple types (eg. functions is now through the same component, skills/languages/certs might be doable as well)
Integration to come later
[TC-813]: https://bcdevex.atlassian.net/browse/TC-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-813] add sections and roles component

---

frontend/src/pages/SplashPage.tsx

[FIX] fix form id

---

frontend/src/components/profile/common/ProfileSectionHeader.tsx
frontend/src/components/profile/details/DetailsSection.tsx
frontend/src/components/profile/details/MemberProfileDetails.tsx
frontend/src/components/profile/details/ProfileDetails.tsx
frontend/src/components/profile/details/index.ts
frontend/src/components/tabs/Details.tsx
frontend/src/hooks/profileData.tsx
frontend/src/pages/profile/MemberProfile.tsx

[TC-802](https://bcdevex.atlassian.net/browse/TC-802)
Objective:
Member data
Viewable edit profile tab
Not editable yet
[TC-802]: https://bcdevex.atlassian.net/browse/TC-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-802] viewable edit profile tab

---

.github/workflows/ci-personnel-faker-dev.yml
.github/workflows/ci-personnel-faker-test.yml
.github/workflows/ci-recommitment-faker-dev.yml
.github/workflows/ci-recommitment-faker-test.yaml
Makefile
backend/src/personnel/personnel.controller.ts
frontend/src/components/ui/form/FormSection.tsx

[CHORE] seed recommitment oc

---

backend/src/form/form.service.ts
backend/src/personnel/personnel.service.ts
frontend/src/hooks/usePersonnel.tsx

Objective:
- update form service to save the food safe and first aid dates as dates
- fix key name for personnel.roles

[FIX] updates to the form service 

---

backend/src/database/entities/emcr/emcr-personnel.entity.ts
backend/src/personnel/personnel.service.ts

Objective:
Update personnel should work here

[FIX] be able to save personnel with relations

---

backend/src/form/form.service.ts

[FIX] fix import

---

backend/src/database/entities/personnel/personnel-language.entity.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/personnel-languages.ro.ts
frontend/src/common/constants.ts
frontend/src/common/helpers.ts
frontend/src/components/profile/forms/MemberProfileEditForm.tsx
frontend/src/components/profile/forms/constants.ts
frontend/src/components/profile/forms/memberFormConfig.tsx
frontend/src/components/profile/sections-roles/MemberItemList.tsx
frontend/src/components/profile/sections-roles/index.ts
frontend/src/components/profile/skills-certifications/MemberSkillsAndCertifications.tsx
frontend/src/components/tabs/Availability.tsx
frontend/src/components/ui/form/FormSection.tsx
frontend/src/hooks/profileData.tsx

[TC-820](https://bcdevex.atlassian.net/browse/TC-820)
Objective:
Saving integration for edit profile tabs
Sections/Certs incoming
[TC-820]: https://bcdevex.atlassian.net/browse/TC-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-820] Edit Profile Tab Saves

---

backend/src/bcws/bcws.service.ts
backend/src/database/entities/recommitment/recommitment.entity.ts
backend/src/emcr/emcr.service.ts
backend/src/personnel/dto/update-personnel-recommitment.dto.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/supervisor.controller.ts
frontend/src/common/constants.ts
frontend/src/common/enums/recommitment-status.ts
frontend/src/common/enums/supervisor-decision.enum.ts
frontend/src/components/profile/details/RecommitmentDetails.tsx
frontend/src/components/profile/forms/types.ts
frontend/src/components/supervisor/ApprovalCell.tsx
frontend/src/components/supervisor/RecommitmentStatusChip.tsx
frontend/src/components/supervisor/constants.ts
frontend/src/components/table/footer/TableFooterPageSelect.tsx
frontend/src/components/ui/classes.ts
frontend/src/components/ui/form/Form.tsx
frontend/src/components/ui/form/FormField.tsx
frontend/src/components/ui/inputs/TextArea.tsx
frontend/src/components/ui/inputs/types.ts
frontend/src/hooks/useSupervisorDashboard.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/supervisor/SupervisorDashboard.tsx
frontend/src/pages/supervisor/SupervisorTable.tsx

[TC-0831](https://bcdevex.atlassian.net/browse/TC-0831)
Objective:
- update supervisor decision
- supervisor dash UI

[TC-831] Supervisor Dash

---

frontend/src/routes/Redirect.tsx

Objective:
- redirect at root url to home if no credentials, and unauthorized if credentials + no role

[FIX] redirect on root

---

frontend/src/components/filters/SingleSelect.tsx
frontend/src/components/filters/date-picker/DatePicker.tsx
frontend/src/components/filters/date-picker/MonthSelector.tsx
frontend/src/components/filters/date-picker/YearSelector.tsx
frontend/src/components/layout/private/Header.tsx
frontend/src/components/layout/private/UserMenu.tsx
frontend/src/components/profile/banners/RecommitmentDashBanner.tsx
frontend/src/components/ui/Dialog.tsx
frontend/src/components/ui/Tabs.tsx
frontend/src/pages/profile/MemberProfile.tsx
frontend/src/pages/supervisor/SupervisorDashboard.tsx
frontend/src/pages/supervisor/SupervisorDashboardHeader.tsx

[TC-820](https://bcdevex.atlassian.net/browse/TC-820)
Objective:
Headless ui updates for deprecated components
[TC-820]: https://bcdevex.atlassian.net/browse/TC-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX] Headless UI Updates

---

backend/src/auth/auth.controller.ts
backend/src/bcws/bcws.service.ts
backend/src/database/entities/bcws/bcws-personnel.entity.ts
backend/src/personnel/personnel.module.ts
backend/src/personnel/personnel.service.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/filters/SingleSelect.tsx
frontend/src/components/filters/date-picker/DatePicker.tsx
frontend/src/components/filters/date-picker/MonthSelector.tsx
frontend/src/components/filters/date-picker/YearSelector.tsx
frontend/src/components/layout/private/Header.tsx
frontend/src/components/layout/private/UserMenu.tsx
frontend/src/components/profile/banners/RecommitmentDashBanner.tsx
frontend/src/components/profile/common/ProfileSectionHeader.tsx
frontend/src/components/profile/sections-roles/MemberProfileEditRoles.tsx
frontend/src/components/profile/sections-roles/index.ts
frontend/src/components/tabs/Availability.tsx
frontend/src/components/ui/Dialog.tsx
frontend/src/components/ui/Tabs.tsx
frontend/src/pages/profile/MemberProfile.tsx
frontend/src/pages/supervisor/SupervisorDashboardHeader.tsx

[TC-820](https://bcdevex.atlassian.net/browse/TC-820)
Objective:
Work incoming to handle EMCR as well
[TC-820]: https://bcdevex.atlassian.net/browse/TC-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-820] Save preferences / sections

---

frontend/cypress/e2e/coordinator.cy.ts
frontend/src/pages/SplashPage.tsx
frontend/src/providers/Role.tsx
frontend/src/routes/AppRoutes.tsx
frontend/src/routes/PrivateRoute.tsx
frontend/src/routes/Redirect.tsx
frontend/src/routes/constants.ts
frontend/src/utils/keycloak.ts

[FIX] redirect

---

frontend/src/routes/Redirect.tsx

Objective:
Member only was redirecting to the wrong place

[FIX] member was redirecting to wrong place

---

backend/src/personnel/dto/create-personnel.dto.ts
backend/src/personnel/personnel.service.ts
frontend/src/components/profile/sections-roles/MemberItemList.tsx
frontend/src/components/profile/skills-certifications/ProfileEditSkills.tsx
frontend/src/components/tabs/Availability.tsx

[TC-820](https://bcdevex.atlassian.net/browse/TC-820)
Objective:
Skills Editing just with the old UI
[TC-820]: https://bcdevex.atlassian.net/browse/TC-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-820] edit skills for member

---

.github/workflows/ci-deploy.yaml

Objective:
- adding manual dev deploy trigger in order to test actions

[CHORE] Manual wf trigger

---

.github/workflows/ci-deploy.yaml
.github/workflows/ci-lint.yaml
.github/workflows/ci-migrations-dev.yaml
.github/workflows/ci-migrations-test.yaml
.github/workflows/ci-personnel-faker-dev.yml
.github/workflows/ci-personnel-faker-test.yml
.github/workflows/ci-promote-test.yaml
.github/workflows/ci-recommitment-faker-dev.yml
.github/workflows/ci-recommitment-faker-test.yaml
.github/workflows/ci-seed-dev.yml
.github/workflows/ci-seed-test.yml

[FIX]  GH Actions

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/profile/sections-roles/MemberProfileEditRoles.tsx

Objective:
Getting rid of some of the `placeholder` is missing errors
Combobox removal of isOpen and other invalid props

[FIX] some errors

---

backend/src/form/form.service.ts
backend/src/form/interface.ts
backend/src/personnel/personnel.service.ts
openshift/server.dc.yml
openshift/server.prep.yml

[FIX] Bugfixes

---

frontend/src/components/profile/banners/RecommitmentProfileBanner.tsx
frontend/src/components/recommitment/Assertions.tsx
frontend/src/components/recommitment/InitialRecommitmentDropdown.tsx
frontend/src/components/recommitment/RecommitmentFormBase.tsx
frontend/src/components/recommitment/SupervisorForm.tsx
frontend/src/components/recommitment/UnableToJoin.tsx
frontend/src/components/recommitment/index.ts
frontend/src/components/recommitment/parq/ParQBase.tsx
frontend/src/components/recommitment/parq/ParQDeclaration.tsx
frontend/src/components/recommitment/parq/ParQFollowUp.tsx
frontend/src/components/recommitment/parq/ParQGeneral.tsx
frontend/src/components/recommitment/parq/ParQIntro.tsx
frontend/src/components/recommitment/parq/index.tsx
frontend/src/pages/profile/MemberProfile.tsx

[TC-804](https://bcdevex.atlassian.net/browse/TC-804)
Objective:
Just UI. 
Integration TBD. Download PARQ TBD.
[TC-804]: https://bcdevex.atlassian.net/browse/TC-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-804] UI for Recommitment form + ParQ

---

backend/src/mail/views/blocks/member-steps.njk
backend/src/mail/views/blocks/parq.njk
backend/src/mail/views/blocks/resources.njk
backend/src/mail/views/blocks/steps.njk
backend/src/mail/views/layout.njk
backend/src/mail/views/member/member-annual-reminder.njk
backend/src/mail/views/member/member-approved.njk
backend/src/mail/views/member/member-denied.njk
backend/src/mail/views/member/member-follow-up.njk
backend/src/mail/views/member/member-no-response.njk
backend/src/mail/views/member/member-reactivate.njk
backend/src/mail/views/supervisor/supervisor-annual-reminder.njk
backend/src/mail/views/supervisor/supervisor-follow-up-reminder.njk

[TC-0834](https://bcdevex.atlassian.net/browse/TC-0834)
Objective:
- email templates

[TC-834] email templates

---

frontend/src/components/profile/banners/RecommitmentDashBanner.tsx
frontend/src/components/profile/banners/RecommitmentProfileBanner.tsx
frontend/src/pages/profile/MemberProfile.tsx
frontend/src/pages/supervisor/SupervisorDashboard.tsx

[TC-0833](https://bcdevex.atlassian.net/browse/TC-0833)
Objective:
- remove time from banners

[TC-833] remove time from banner

---

frontend/src/components/table/footer/TableFooterNav.tsx
frontend/src/pages/dashboard/Dashboard.tsx

[TC-833](https://bcdevex.atlassian.net/browse/TC-833)
Objective:
- fix pagination bug
[TC-833]: https://bcdevex.atlassian.net/browse/TC-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-833] FIX pagination bug

---

.env.example
.github/workflows/ci-dev-recommitment-test.yml
.github/workflows/ci-test-recommitment-test.yaml
Makefile
backend/package.json
backend/src/mail/mail.service.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/recommitment.ro.ts
backend/src/recommitment/cron-test.service.ts
backend/src/recommitment/cron.service.ts
backend/src/recommitment/recommitment.module.ts
backend/src/recommitment/recommitment.service.ts
backend/src/recommitment/test-handler.ts
backend/test/app.spec.ts
docker-compose.ci.yml
docker-compose.yml
frontend/src/components/supervisor/ApprovalCell.tsx
frontend/src/pages/profile/MemberProfile.tsx

[TC-0834](https://bcdevex.atlassian.net/browse/TC-0834)
Objective:
- automated notifications
- testing endpoint

[TC-834] automated emails + testing svc

---

backend/src/recommitment/recommitment.service.ts
frontend/src/components/recommitment/RecommitmentFormBase.tsx
frontend/src/hooks/useRecommitment.tsx
frontend/src/pages/profile/MemberProfile.tsx

[TC-804](https://bcdevex.atlassian.net/browse/TC-804)
Objective:
[TC-804]: https://bcdevex.atlassian.net/browse/TC-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-804] recommitment integration

---

frontend/src/components/profile/banners/RecommitmentDashBanner.tsx

Objective:
- fix formatted year on dash banner

[FIX]: banner

---

frontend/src/common/enums/supervisor-decision.enum.ts
frontend/src/components/supervisor/ApprovalCell.tsx
frontend/src/components/supervisor/constants.ts
frontend/src/components/ui/form/FormField.tsx
frontend/src/pages/supervisor/SupervisorDashboard.tsx

[TC-0849](https://bcdevex.atlassian.net/browse/TC-0849)
Objective:
- bug fixes for supervisor dash UI

[TC-849] Supervisor Dash UI

---

Makefile
backend/src/database/entities/recommitment/recommitment-cycle.entity.ts
backend/src/database/seed/seed-recommitment.ts
backend/src/recommitment/cron.service.ts
backend/src/recommitment/recommitment.service.ts

Objective:
- only send one email to supervisors even if multiple members/programs for follow up reminder

[FIX]: supervisor follow up email generation

---

frontend/src/components/profile/scheduler/MemberScheduler.tsx
frontend/src/components/profile/scheduler/MemberSchedulerPopUp.tsx
frontend/src/components/profile/scheduler/index.ts

[TC-679](https://bcdevex.atlassian.net/browse/TC-679)
Objective:
[TC-679]: https://bcdevex.atlassian.net/browse/TC-679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-679] scheduler ui for members

---

frontend/src/components/profile/banners/RecommitmentProfileBanner.tsx
frontend/src/components/recommitment/RecommitmentFormBase.tsx
frontend/src/components/recommitment/UnableToJoin.tsx

Objective:
Buttons should bring up modal again
Fix for reasons

[CHORE] Recommitment Banner Buttons

---

.env.example
Makefile
backend/src/jobs/automated_reminders.ts
backend/src/jobs/end_recommitment.ts
backend/src/jobs/start_recommitment.ts
backend/src/mail/constants.ts
backend/src/mail/mail.ro.ts
backend/src/mail/mail.service.ts
backend/src/personnel/dto/update-personnel-recommitment.dto.ts
backend/src/recommitment/recommitment.controller.ts
backend/src/recommitment/recommitment.service.ts
backend/src/views/blocks/env.njk
backend/src/views/blocks/member-button.njk
backend/src/views/blocks/program-contact.njk
backend/src/views/blocks/supervisor-button.njk
backend/src/views/layout.njk
backend/src/views/member/member-annual-reminder.njk
backend/src/views/member/member-approved.njk
backend/src/views/member/member-supervisor-no-response.njk
backend/src/views/supervisor/supervisor-request.njk
frontend/src/components/recommitment/RecommitmentFormBase.tsx
frontend/src/components/supervisor/ApprovalCell.tsx
frontend/src/hooks/useMemberProfile.tsx
frontend/src/hooks/useSupervisorDashboard.tsx
frontend/src/pages/profile/MemberProfile.tsx
openshift/cron-end-recommitment.yml
openshift/cron-notifications.yml
openshift/cron-start-recommitment.yml

Objective:
- simplify the filtering logic
- add more logs
- update limit/request for oc
- fix env var format 
- update tags for easy querying
- update subject line of emails
- create supervisor no response template
- fix supervisor/member reason in the db
- refetch data after submit from banners

[CHORE] Fix jobs - better logging - no undefined

---

backend/src/views/blocks/resources.njk
backend/src/views/supervisor/supervisor-annual-reminder.njk
backend/src/views/supervisor/supervisor-follow-up-reminder.njk
backend/src/views/supervisor/supervisor-request.njk

Objective:
- additions to sup' templates

[CHORE]: additions to supervisor template

---

frontend/src/components/profile/sections-roles/MemberProfileEditRoles.tsx
frontend/src/components/profile/sections-roles/RolesGuide.tsx
frontend/src/components/ui/Dialog.tsx

Objective:
- pop up for roles/sections descriptions on member profile now properly displaying BCWS

[FIX] Roles Descriptions Pop up modal 

---

frontend/src/components/supervisor/ApprovalCell.tsx
frontend/src/components/ui/form/FormField.tsx
frontend/src/components/ui/inputs/TextArea.tsx

[TC-823](https://bcdevex.atlassian.net/browse/TC-823)
Objective:
- validation on comments field
[TC-823]: https://bcdevex.atlassian.net/browse/TC-823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-823] validation

---

backend/src/jobs/seed-recommitment.ts
backend/src/jobs/start_recommitment.ts
backend/src/mail/constants.ts
openshift/cron-start-recommitment.yml

[FIX] changed start-recommitment-job

---

Makefile
backend/src/jobs/start_recommitment.ts
backend/src/personnel/dto/update-personnel-recommitment.dto.ts
backend/src/personnel/personnel.service.ts
backend/src/recommitment/recommitment.service.ts
backend/src/views/blocks/member-steps.njk
docker-compose.yml
frontend/src/common/constants.ts
frontend/src/components/supervisor/ApprovalCell.tsx
frontend/src/hooks/useRecommitment.tsx
frontend/src/hooks/useSupervisorDashboard.tsx
frontend/src/pages/supervisor/SupervisorDashboard.tsx
frontend/src/pages/supervisor/SupervisorTable.tsx

Objective:
- supervisor dash will only show ACTIVE members 
- fix pagination
- only sending one email to member/supervisor on test env for bulk

[FIX] - supervisor dash bugs

---

backend/src/jobs/end_recommitment.ts
backend/src/jobs/start_recommitment.ts

[FIX] - end recommitment on job run,regardless of db end date

---

backend/src/bcws/bcws.service.ts
backend/src/emcr/emcr.service.ts
frontend/src/components/table/body/TableBodyCell.tsx
frontend/src/components/table/interface.ts
frontend/src/components/ui/Table.tsx
frontend/src/hooks/useTable.tsx
frontend/src/pages/dashboard/Dashboard.tsx
frontend/src/pages/dashboard/MemberStatusGuide.tsx
frontend/src/pages/dashboard/constants.ts
frontend/tailwind.config.cjs

[TC-0855](https://bcdevex.atlassian.net/browse/TC-0855)
Objective:
- showing member status on dashboard
- member status guide on coord dashboard view

[TC-855] coord dashboard - member status guide

---

backend/src/jobs/end_recommitment.ts

Objective:
- forgot to set this to end at PST 😅

[FIX] - end recommitment PST

---

backend/src/jobs/automated_reminders.ts

Objective:
- && not || for check date

[FIX] notification cron check

---

backend/src/personnel/personnel.service.ts

[FIX] move filter to fix 500 error

---

backend/src/app.controller.ts
frontend/src/components/profile/details/Detail.tsx
frontend/src/components/profile/details/DetailsSection.tsx
frontend/src/components/profile/scheduler/MemberSchedulerControl.tsx
frontend/src/components/profile/sections-roles/MemberItemList.tsx
frontend/src/components/profile/skills-certifications/MemberSkillsAndCertifications.tsx
frontend/src/components/tabs/Availability.tsx
frontend/src/components/tabs/MemberProfileDetails.tsx
frontend/src/hooks/profileData.tsx
frontend/src/pages/profile/types.ts

[TC-840](https://bcdevex.atlassian.net/browse/TC-840)
[TC-854](https://bcdevex.atlassian.net/browse/TC-854)
[TC-842](https://bcdevex.atlassian.net/browse/TC-842)
[TC-841](https://bcdevex.atlassian.net/browse/TC-841)
[TC-862](https://bcdevex.atlassian.net/browse/TC-862)
Objective:
[TC-840]: https://bcdevex.atlassian.net/browse/TC-840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TC-854]: https://bcdevex.atlassian.net/browse/TC-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TC-842]: https://bcdevex.atlassian.net/browse/TC-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TC-841]: https://bcdevex.atlassian.net/browse/TC-841?atlOrigin=eyJpIjoiNWRkNT …

[TC-840] Bunch of bugfixes

---

backend/src/bcws/dto/create-bcws-personnel.dto.ts
backend/src/bcws/ro/bcws-personnel.ro.ts
backend/src/database/entities/bcws/bcws-personnel.entity.ts
backend/src/database/entities/emcr/emcr-personnel.entity.ts
backend/src/database/migrations/1737012316279-third-choice-migration.ts
backend/src/emcr/dto/create-emcr-personnel.dto.ts
backend/src/emcr/ro/emcr-personnel.ro.ts
backend/src/personnel/personnel.service.ts
frontend/src/common/constants.ts
frontend/src/components/profile/sections-roles/MemberProfileEditRoles.tsx
frontend/src/components/tabs/Availability.tsx
frontend/src/pages/profile/MemberProfile.tsx

Objective:
Third Choice section for BCWS
Section preferences for EMCR
RO is named Function due to the way the frontend `.emcr` and `.bcws` is used (ie. as Partial<Personnel>)

[TC-825] third choice section, emcr section preferences

---

frontend/src/common/enums/supervisor-decision.enum.ts
frontend/src/components/supervisor/ApprovalCell.tsx
frontend/src/components/supervisor/constants.ts

[TC-0850](https://bcdevex.atlassian.net/browse/TC-0850)
Objective:
- form validation on supervisor declined form
-

[TC-850] Supervisor form validation

---

frontend/src/components/table/body/TableBodyCell.tsx

Objective:
- label for recommitment on dash

[FIX] dash label for recommitment

---

backend/src/recommitment/recommitment.service.ts
frontend/src/hooks/profileData.tsx

[TC-0865](https://bcdevex.atlassian.net/browse/TC-0865)
Objective:
- show one or both programs membership/recommitment info on member profile

[TC-865] membership info on member profile

---

frontend/src/pages/profile/MemberProfile.tsx

[TC-0880](https://bcdevex.atlassian.net/browse/TC-0880)
Objective:
- uppercase program in form title

[TC-880] fix casing on form title

---

frontend/src/common/types.ts
frontend/src/components/recommitment/InitialRecommitmentDropdown.tsx
frontend/src/components/recommitment/RecommitmentFormBase.tsx
frontend/src/components/recommitment/UnableToJoin.tsx
frontend/src/components/ui/Button.tsx
frontend/src/hooks/helpers.ts
frontend/src/pages/dashboard/columns.ts

[TC-761](https://bcdevex.atlassian.net/browse/TC-761)
[TC-902](https://bcdevex.atlassian.net/browse/TC-902)
[TC-903](https://bcdevex.atlassian.net/browse/TC-903)
[TC-904](https://bcdevex.atlassian.net/browse/TC-904)
[TC-905](https://bcdevex.atlassian.net/browse/TC-905)
Objective:
[TC-761]: https://bcdevex.atlassian.net/browse/TC-761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TC-902]: https://bcdevex.atlassian.net/browse/TC-902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TC-903]: https://bcdevex.atlassian.net/browse/TC-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TC-904]: https://bcdevex.atlassian.net/browse/TC-904?atlOrigin=eyJpIjoiNWRkNT …

[TC-902] Various UI fixes

---

frontend/src/components/profile/RecommitmentBanner.tsx
frontend/src/components/profile/banners/RecommitmentProfileBanner.tsx

[TC-0899](https://bcdevex.atlassian.net/browse/TC-0899)
Objective:
- showing banner program if status is different

[TC-899] member profile banners

---

frontend/src/components/profile/common/ProfileSectionHeader.tsx
frontend/src/components/profile/details/DetailsSection.tsx
frontend/src/components/profile/header/ProfileMemberHeader.tsx
frontend/src/components/profile/header/helpers.tsx
frontend/src/components/profile/scheduler/MemberScheduler.tsx
frontend/src/components/profile/scheduler/MemberSchedulerControl.tsx
frontend/src/components/profile/scheduler/MemberSchedulerHeader.tsx
frontend/src/components/profile/scheduler/MemberSchedulerKey.tsx
frontend/src/components/profile/sections-roles/MemberItemList.tsx
frontend/src/components/tabs/Availability.tsx
frontend/src/components/tabs/MemberProfileDetails.tsx
frontend/src/components/ui/Status.tsx
frontend/src/pages/profile/MemberProfile.tsx

[TC-0863](https://bcdevex.atlassian.net/browse/TC-0863)
Objective:
- profile status tag showing for each program
- updated a couple of button/text colours
- added the grey border around the profile components

[TC-863] - Profile status per program

---

frontend/src/components/supervisor/constants.ts
frontend/src/components/ui/Icons.tsx
frontend/src/pages/constants.tsx
frontend/src/pages/supervisor/SupervisorDashboard.tsx
frontend/src/pages/supervisor/SupervisorDashboardHeader.tsx

[TC-0916](https://bcdevex.atlassian.net/browse/TC-0916)
Objective:
- icon
- copy

[TC-916] Supervisor Dash copy fixes 

---

backend/src/database/entities/audit.entity.ts
backend/src/database/migrations/1737162090179-audit-entity-null-migration.ts

[FIX] make audit entity id nullable

---

.github/workflows/ci-migrations-test.yaml
.github/workflows/ci-personnel-faker-dev.yml
backend/src/database/seed/create-bcws.ts
backend/src/database/seed/create-emcr.ts
backend/src/database/seed/create-personnel.ts
backend/src/database/seed/seed-bcws.ts
backend/src/database/seed/seed-both.ts
backend/src/database/seed/seed-emcr.ts

[CHORE] updated faker seed fnc for local/dev/test

---

.env.example
Makefile
backend/src/bcws/bcws.service.ts
backend/src/emcr/emcr.service.ts
backend/src/jobs/automated_reminders.ts
backend/src/jobs/end_recommitment.ts
backend/src/jobs/start_recommitment.ts
backend/src/mail/mail.service.ts
backend/src/personnel/personnel.service.ts
backend/src/recommitment/recommitment.module.ts
backend/src/recommitment/recommitment.service.ts
docker-compose.yml
openshift/cron-end-recommitment.yml
openshift/cron-notifications.yml
openshift/cron-start-recommitment.yml
openshift/server.dc.yml
openshift/server.prep.yml

Objective:
- updated jobs for recommitment

[FIX] recommitment prod run status update

---

backend/src/bcws/bcws.service.ts
backend/src/personnel/personnel.service.ts
frontend/src/hooks/usePersonnel.tsx

[TC-928](https://bcdevex.atlassian.net/browse/TC-928)
Objective:
[TC-928]: https://bcdevex.atlassian.net/browse/TC-928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-928] bcws coordinators edit profile

---

backend/src/bcws/bcws.service.ts
backend/src/emcr/dto/create-emcr-personnel.dto.ts
backend/src/emcr/emcr.controller.ts
backend/src/emcr/emcr.service.ts
backend/src/personnel/personnel.service.ts
frontend/src/components/profile/details/DetailsSection.tsx
frontend/src/components/profile/forms/constants.ts
frontend/src/components/profile/forms/formConfig.tsx
frontend/src/components/ui/Banner.tsx
frontend/src/hooks/usePersonnel.tsx

[TC-0928](https://bcdevex.atlassian.net/browse/TC-0928)
Objective:
- update emcr personnel from coordinator dash
- TODO: name in the profile header does not refresh when changed, but all other data on page refreshes. (Also, Not sure why the coordinators can change the persons name but the member cannot ??? )

[TC-928] EMCR update

---

backend/src/views/blocks/member-steps.njk
backend/src/views/blocks/steps.njk
backend/src/views/member/member-annual-reminder.njk
backend/src/views/member/member-approved.njk

[FIX] Template fixes

---

backend/src/jobs/automated_reminders.ts
backend/src/jobs/end_recommitment.ts
backend/src/jobs/start_recommitment.ts
backend/src/main.ts
backend/src/views/test/blocks/env.njk
backend/src/views/test/layout.njk
backend/src/views/test/member/member-annual-reminder.njk
backend/src/views/test/member/member-approved.njk
backend/src/views/test/member/member-declined.njk
backend/src/views/test/member/member-denied.njk
backend/src/views/test/member/member-follow-up.njk
backend/src/views/test/member/member-no-response.njk
backend/src/views/test/member/member-reactivate.njk
backend/src/views/test/member/member-supervisor-no-response.njk
backend/src/views/test/supervisor/supervisor-annual-reminder.njk
backend/src/views/test/supervisor/supervisor-follow-up-reminder.njk
backend/src/views/test/supervisor/supervisor-request.njk

Objective:
- blank templates with only template name to use on dev

[CHORE] test-email templates

---

backend/src/mail/mail.service.ts

Objective:
- remove null supervisor emails

[FIX] remove null supervisor

---

backend/src/jobs/automated_reminders.ts
backend/src/jobs/end_recommitment.ts
backend/src/jobs/start_recommitment.ts
openshift/cron-end-recommitment.yml
openshift/cron-notifications.yml
openshift/cron-start-recommitment.yml

Objective:
- log all email addresses
- update resources

[CHORE] logs

---

openshift/client.dc.yml
openshift/cron-end-recommitment.yml
openshift/cron-notifications.yml
openshift/cron-start-recommitment.yml

[CHORE] limits

---

openshift/cron-start-recommitment.yml

Objective:
- remove hardcoded value

[FIX] cron image name

---

backend/src/personnel/personnel.service.ts
frontend/src/components/recommitment/RecommitmentFormBase.tsx
frontend/src/components/recommitment/SupervisorForm.tsx

[FIX] supervisor null check

---

frontend/src/components/profile/forms/constants.ts

[FIX] supe validation on form

---

backend/src/mail/mail.service.ts

[FIX] avoid logging error

---

.github/workflows/ci-promote-test.yaml
.github/workflows/ci-promote.prod.yaml

[CHORE] gh actions to v4

---

Makefile
openshift/cron-end-recommitment.yml
openshift/cron-notifications.yml
openshift/cron-start-recommitment.yml

Objective:
- update jobs to not use any of our long time compute resources

[FIX] update jobs

---

backend/src/mail/mail.service.ts

[FIX] email chunks

---

backend/src/recommitment/recommitment.service.ts

Objective:
- supervisor email fix when member commits + updates supervisor info

[FIX] supervisor email fix

---

frontend/src/components/profile/common/ProfileToggle.tsx
frontend/src/components/toggle/Toggle.tsx
frontend/src/pages/profile/Profile.tsx

[CHORE] Chore disable toggle

---

frontend/src/components/profile/RecommitmentBanner.tsx
frontend/src/components/profile/banners/RecommitmentProfileBanner.tsx
frontend/src/pages/profile/MemberProfile.tsx

[FIX] close banner on member profile

---

backend/src/views/blocks/supervisor-resources.njk

Objective:
- supervisor link fix

[FIX] supervisor links

---

.github/workflows/ci-promote-test.yaml

Objective:
- manual trigger to deploy test from git hub instead of only from local

[CHORE] manual test deploy trigger

---

openshift/cron-notifications.yml

[FIX] update cron img ref

---

backend/src/bcws/bcws.service.ts
backend/src/common/enums/status.enum.ts
backend/src/emcr/emcr.service.ts
backend/src/personnel/dto/get-personnel.dto.ts
backend/src/personnel/personnel.service.ts
frontend/src/common/constants.ts
frontend/src/common/enums/status.enum.ts
frontend/src/components/filters/StatusFilter.tsx
frontend/src/components/table/footer/TableFooterNav.tsx
frontend/src/components/ui/Table.tsx
frontend/src/components/ui/Tabs.tsx
frontend/src/pages/dashboard/Dashboard.tsx

[TC-781](https://bcdevex.atlassian.net/browse/TC-781)
Objective:
- filter by recom status/all/new
[TC-781]: https://bcdevex.atlassian.net/browse/TC-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-781] filter active personnel status

---

backend/src/mail/mail.service.ts

[FIX] fix triggered email send

---

frontend/src/common/enums/recommitment-status.ts
frontend/src/components/profile/details/RecommitmentDetails.tsx

Objective:
- display recommitment info coord profile

[FIX] recommitment field profile

---

backend/src/personnel/dto/update-personnel-recommitment.dto.ts
frontend/src/components/recommitment/RecommitmentFormBase.tsx
frontend/src/components/recommitment/SupervisorForm.tsx
frontend/src/hooks/useRecommitment.tsx

Objective:
- using @Type() from class transformer in order to validate nested DTO's
- added field validation on supervisor section of recommitment form
- added an additional form validation on the recommitment base
- returning an error on form submission and showing error banner in case the patch request fails

[FIX] supervisor phone

---

frontend/src/components/profile/functions/ProfileFunctions.tsx
frontend/src/components/profile/sections-roles/MemberItemList.tsx
frontend/src/components/profile/sections-roles/MemberProfileEditRoles.tsx
frontend/src/components/profile/sections-roles/SectionsAndRoles.tsx
frontend/src/components/tabs/Availability.tsx

[TC-825](https://bcdevex.atlassian.net/browse/TC-825)
Objective:
Show third choice BCWS
Show all choices EMCR for members
Show EMCR choices for coords / LOs
[TC-825]: https://bcdevex.atlassian.net/browse/TC-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-825] display choice of section / function

---

backend/src/form/form.service.ts
backend/src/recommitment/recommitment.service.ts

Objective:
Update supervisor email in the updateSupervisorInformation function and in creating

[FIX] supervisor email lowercase

---

frontend/src/common/enums/recommitment-status.ts
frontend/src/components/supervisor/ApprovalCell.tsx
frontend/src/components/supervisor/RecommitmentStatusChip.tsx
frontend/src/pages/supervisor/SupervisorDashboard.tsx
frontend/src/pages/supervisor/SupervisorTable.tsx

Objective:
- fix the recommitment status tag 
- fix column widths
- add tooltip to explain the status's

[CHORE] supervisor table clean up

---

frontend/src/providers/Auth.tsx

[TC-0951](https://bcdevex.atlassian.net/browse/TC-0951)
Objective:
- fallback screen if backend container is unavailable (does not resolve the issue if the frontend is down so this is only a partial resolution)

[TC-951] - fallback screen

---

frontend/src/components/profile/banners/NewApplicantBanner.tsx

Objective:
- date approved bug

[FIX] date approved bug

---

frontend/src/components/layout/private/Layout.tsx
frontend/src/components/layout/public/Layout.tsx

Objective:
- set min height for content to avoid footer flashing on screen

[FIX] fix layout shift

---

frontend/src/components/recommitment/RecommitmentFormBase.tsx

[TC-994](https://bcdevex.atlassian.net/browse/TC-994)
Objective:
[TC-994]: https://bcdevex.atlassian.net/browse/TC-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-994] Decline recommitment with no supervisor

---

backend/src/mail/constants.ts
backend/src/views/blocks/member-steps.njk
frontend/src/components/profile/RecommitmentBanner.tsx
frontend/src/components/profile/banners/RecommitmentProfileBanner.tsx

Objective:
- email copy update

[CHORE] email copy update

---

backend/src/views/blocks/member-steps.njk
backend/src/views/blocks/steps.njk

[TC-0976](https://bcdevex.atlassian.net/browse/TC-0976)
Objective:
**DRAFT**
- waiting for approval on the member template change

[TC-976] DRAFT: template link updates

---

frontend/src/pages/supervisor/SupervisorApprovalForm.tsx

[TC-1030](https://bcdevex.atlassian.net/browse/TC-1030)
Objective:
- bugs found by QA on test

[TC-1030] fix close modal on sup dash

---

frontend/src/components/supervisor/constants.ts
frontend/src/pages/supervisor/SupervisorApprovalForm.tsx
openshift/cron-notifications.yml
openshift/cron-start-recommitment.yml

Objective:
- supervisor declined modal

[FIX] Supervisor Decline Modal

---

backend/src/recommitment/recommitment.service.ts

[FIX] proper permissions for update

---

backend/src/database/entities/recommitment/recommitment-cycle.entity.ts
backend/src/database/entities/recommitment/recommitment-cycle.ro.ts
backend/src/database/migrations/1739261137836-recommitment-reinitiation-migration.ts
backend/src/recommitment/recommitment.service.ts
frontend/src/common/constants.ts
frontend/src/components/profile/common/ProfileToggle.tsx
frontend/src/components/ui/classes.ts
frontend/src/hooks/usePersonnel.tsx
frontend/src/hooks/useRecommitment.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/RecommitmentConfirmation.tsx
frontend/src/pages/profile/RecommitmentReinitiationConfirmation.tsx

[TC-960](https://bcdevex.atlassian.net/browse/TC-960)
Objective:
Allow coordinators to reinitialize recommitment for inactive member
NEEDS MIGRATION
TODO:
- Email content for supervisor
- Tooltip (?) necessary?
[TC-960]: https://bcdevex.atlassian.net/browse/TC-960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-960] recommitment reinitation by coord

---

frontend/src/components/filters/AvailabilityFilter.tsx
frontend/src/components/filters/SingleSelect.tsx
frontend/src/components/filters/classes.ts
frontend/src/components/recommitment/InitialRecommitmentDropdown.tsx
frontend/src/components/ui/SingleSelect.tsx
frontend/src/pages/dashboard/DashboardFilters.tsx
frontend/src/utils/helpers.ts

1) refactor: make SingleSelect component more generic
- Made changes to the SingleSelect component to make it more generic
- Used the SingleSelect component in InitialRecommitmentDropdown
instead of the default react/tailwind Select (not matching our
specifications)
- Reused the SingleSelect component in DashboardFilters, changed
the props to accommodate the new structure
- Added a `getLabelFromValue` helper method in `helpers.ts`
2) feat: added red asterisk after the question
- Navigate to `/dashboard`
- Find the `Availability` select and make sure it is working as before (using Chips and applying filters correctly, disabling/enabling the date selector when picked)
- Navigate to `/profile` and click `Make Recommitment Decision`
- In the popped up modal, click on the select field make …

Fix/TC-897 Refactor <SingleSelect>

---

backend/src/bcws/bcws.controller.ts
backend/src/bcws/bcws.service.ts
backend/src/bcws/dto/create-bcws-personnel-roles.dto.ts
backend/src/bcws/dto/helpers.ts
backend/src/bcws/dto/update-bcws-personnel-roles.dto.ts
backend/src/database/entities/bcws/bcws-personnel-roles.entity.ts
backend/src/database/entities/emcr/emcr-function-experience.entity.ts
backend/src/database/entities/emcr/emcr-personnel.entity.ts
backend/src/database/entities/emcr/emcr-training.entity.ts
backend/src/database/entities/personnel/personnel-certification.entity.ts
backend/src/database/seed/helpers.ts
backend/src/emcr/dto/create-emcr-personnel.dto.ts
backend/src/emcr/dto/helpers.ts
backend/src/emcr/emcr.controller.ts
backend/src/emcr/emcr.service.ts
backend/src/form/form.service.ts
backend/src/personnel/dto/skills/update-personnel-skills.dto.ts
backend/src/personnel/dto/update-personnel.dto.ts
backend/src/personnel/helpers.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.module.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/update-preferences.dto.ts
backend/src/recommitment/recommitment.controller.ts
backend/src/recommitment/recommitment.service.ts

Objective:
- BE updated to use the new DTO's
- split up the update endpoints

[CHORE] Update BE to use new DTOS

---

frontend/src/components/ui/Dialog.tsx
frontend/src/pages/profile/RecommitmentReinitiationConfirmation.tsx

[TC-960](https://bcdevex.atlassian.net/browse/TC-960)
Objective:
Adjust dialog to match with new design
[TC-960]: https://bcdevex.atlassian.net/browse/TC-960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-960] recommitment confirm dialog

---

frontend/src/components/search/Search.tsx

[TC-935](https://bcdevex.atlassian.net/browse/TC-935)
Objective:
Use useCallback
So it only makes the request once
May help performance too
[TC-935]: https://bcdevex.atlassian.net/browse/TC-935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX] useCallback for name search

---

frontend/src/hooks/useRecommitment.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/RecommitmentReinitiationTooltip.tsx

[TC-960](https://bcdevex.atlassian.net/browse/TC-960)
Objective:
Add tooltip button and dialog
[TC-960]: https://bcdevex.atlassian.net/browse/TC-960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX] Tooltip for reinitiation

---

backend/src/common/enums/status.enum.ts
backend/src/personnel/dto/get-personnel.dto.ts
backend/src/personnel/personnel.service.ts

[TC-949](https://bcdevex.atlassian.net/browse/TC-949)
Objective:
- BE changes to be merged into upstream branch prior to upstream merging onto main
[TC-949]: https://bcdevex.atlassian.net/browse/TC-949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-949] BE changes inactive recommitment status filter

---

frontend/src/pages/dashboard/constants.ts

Tickets:
https://emcr.atlassian.net/browse/TC-993
https://emcr.atlassian.net/browse/TC-1066
Description:
- Removed the unused status descriptions according to the ticket
- Changed `New` description according to the ticket
- Renamed CORE to CORE Team
Screenshots:

[TC-993][TC-1066] Change Member Status Guide in the Coordinators' Dashboard

---

frontend/src/components/profile/scheduler/Scheduler.tsx

[TC-932](https://bcdevex.atlassian.net/browse/TC-932)
[TC-932]: https://bcdevex.atlassian.net/browse/TC-932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-932] available click as new date

---

frontend/src/components/profile/forms/constants.ts
frontend/src/components/profile/forms/memberFormConfig.tsx

[TC-1069](https://bcdevex.atlassian.net/browse/TC-1069)
Objective:
- coord can edit liaison info

[TC-1069] Fix coord edit liaison

---

backend/src/jobs/end_recommitment.ts
openshift/cron-end-recommitment.yml

Objective:
- FIX env var and cron yml

[FIX] fix env var

---

backend/src/bcws/bcws.service.ts
backend/src/emcr/emcr.service.ts
backend/src/recommitment/recommitment.service.ts

Objective:
- revision after refactor yesterday

[FIX] bulk status update

---

frontend/src/hooks/useRecommitment.tsx

Objective:
- showing button if today is between recom end and recom reinit end

[FIX] end date

---

frontend/src/hooks/useRecommitment.tsx
frontend/src/pages/supervisor/SupervisorApprovalForm.tsx
frontend/src/pages/supervisor/SupervisorDashboard.tsx
frontend/src/pages/supervisor/SupervisorDashboardHeader.tsx

[TC-1028](https://bcdevex.atlassian.net/browse/TC-1028)
Objective:
- post recommitment supervisor dashboard

[TC-1028] supervisor empty state

---

backend/src/recommitment/recommitment.controller.ts
backend/src/recommitment/recommitment.service.ts
frontend/src/components/recommitment/RecommitmentFormBase.tsx
frontend/src/components/recommitment/SupervisorForm.tsx
frontend/src/components/supervisor/constants.ts
frontend/src/hooks/useRecommitment.tsx
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/supervisor/SupervisorApprovalForm.tsx

Objective:
- split the recommitment end points

[FIX] BE changes for supervisor/ member decision

---

backend/src/recommitment/recommitment.controller.ts
backend/src/recommitment/recommitment.service.ts
frontend/src/pages/supervisor/SupervisorApprovalForm.tsx

[FIX] set status to active if during reinitiation

---

backend/src/mail/constants.ts
backend/src/recommitment/recommitment.service.ts

[TC-1085](https://bcdevex.atlassian.net/browse/TC-1085)
Objective:

[TC-1085] reset recommitment for both programs

---

frontend/src/pages/intake-form/fields.ts

[TC-1003] IntakeFormData Interface

---

backend/src/recommitment/recommitment.service.ts
frontend/src/components/profile/banners/RecommitmentProfileBanner.tsx
frontend/src/components/tabs/Availability.tsx

Objective:
Also adds fixes to banners

[FIX] other program reinitiation

---

frontend/src/components/profile/scheduler/MemberSchedulerPopUp.tsx

Objective:
- fix update unavailable bug for members

[FIX] fix update schedule bug

---

frontend/src/pages/intake-form/FormSections.tsx
frontend/src/pages/intake-form/IntakeForm.tsx
frontend/src/pages/intake-form/components/SelectField.tsx
frontend/src/pages/intake-form/components/TextField.tsx
frontend/src/pages/intake-form/fields.ts
frontend/src/pages/intake-form/tabs.tsx
frontend/src/pages/intake-form/types.ts

[TC-1003](https://bcdevex.atlassian.net/browse/TC-1003)
Objective:
- custom field types with dynamic render
[TC-1003]: https://bcdevex.atlassian.net/browse/TC-1003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-1003] Formik Field

---

backend/src/bcws/dto/update-bcws-personnel-roles.dto.ts
frontend/src/components/profile/sections-roles/ProfileEditRoles.tsx
frontend/src/hooks/usePersonnel.tsx

[TC-1068](https://bcdevex.atlassian.net/browse/TC-1068)
Objective:
- remove second choice role bcws coords

[TC-1068] bcws coord update role pref

---

backend/src/personnel/personnel.service.ts
frontend/src/components/profile/scheduler/MemberScheduler.tsx
frontend/src/components/tabs/Availability.tsx
frontend/src/hooks/useAvailability.tsx

[TC-1093](https://bcdevex.atlassian.net/browse/TC-1093)
Objective:
- scheduler copy update
- scheduler showing confirmed if <= confirmed until date

[TC-1093] scheduler bugs

---

backend/src/personnel/personnel.service.ts

[TC-1094](https://bcdevex.atlassian.net/browse/TC-1094)
Objective:
- missed this one

[TC-1094] available date fix

---

backend/src/recommitment/recommitment.service.ts

Objective:
Emails might be invalid

[FIX] recommitment email

---

backend/src/common/chips/sample-data.ts
backend/src/jobs/chips.ts
backend/src/modules/chips-app.module.ts
backend/src/personnel/personnel.service.ts
openshift/cron-chips.yml

[TC-1106](https://bcdevex.atlassian.net/browse/TC-1106)
Objective:

[TC-1106] chips job

---

backend/package-lock.json
backend/package.json
frontend/package-lock.json
frontend/package.json
notebooks/package-lock.json
notebooks/package.json

[FIX] update vulnerable packages

---

backend/src/app.controller.ts
backend/src/common/chips/chips-response.ts
backend/src/jobs/chips.ts
backend/src/personnel/personnel.service.ts

Using the right endpoints
Objective:

[FIX] chips endpoint fix

---

backend/src/views/blocks/member-links.njk
backend/src/views/blocks/member-steps-followup.njk
backend/src/views/blocks/member-steps.njk
backend/src/views/blocks/resources.njk
backend/src/views/blocks/steps.njk
backend/src/views/member/member-approved.njk

Objective:
- update links to a single link with all manuals
- bold member reminder to update calendar

[FIX] Broken links + bolded text

---

frontend/src/components/profile/scheduler/MemberSchedulerPopUp.tsx
frontend/src/hooks/useSchedulerDialog.tsx

Objective:
- members who have confirmed can also add unavailable blocks

[FIX] Member scheduler fix

---

backend/src/app.controller.ts
backend/src/jobs/chips.ts
backend/src/personnel/personnel.service.ts

Objective:
Currently, training data comes back to us as a string. This should save them properly now.

[FIX] training data as string

---

backend/src/app.controller.ts
backend/src/personnel/personnel.service.ts

Objective:
Got word from peoplesoft on the proper formatting for the request

[FIX] use chips filter param

---

backend/src/jobs/chips.ts
backend/src/personnel/personnel.service.ts

[FIX] setting chips personnel flag

---

.github/workflows/ci-promote.prod.yaml
.github/workflows/ci-tests.yaml

Objective:
- should resolve failing GHA step on promote prod (changed the oc install command)

[FIX] Update ci-prmote-prod.yml

---

frontend/src/components/profile/scheduler/MemberScheduler.tsx
frontend/src/components/profile/scheduler/MemberSchedulerControl.tsx
frontend/src/components/profile/scheduler/MemberSchedulerPopUp.tsx
frontend/src/components/tabs/Availability.tsx
frontend/src/hooks/useSchedulerDialog.tsx

[TC-1109](https://bcdevex.atlassian.net/browse/TC-1109)
Objective:

[TC-1109] Scheduler bug

---

backend/src/jobs/chips.ts
backend/src/personnel/personnel.service.ts

Objective:
Thought about it, and maybe we don't need to care about updatedAt for updating CHIPS

[FIX] remove updated at clause for CHIPS

---

frontend/src/components/ui/Alert.tsx
frontend/src/components/ui/Icons.tsx
frontend/src/pages/intake-form/IntakeForm.tsx
frontend/src/pages/intake-form/components/FormButtonNavigation.tsx
frontend/src/providers/Alert.tsx
frontend/src/routes/PrivateRoute.tsx

[TC-10000](https://bcdevex.atlassian.net/browse/TC-1000)
Objective:
- save progress alert

[TC-1000]  Form Save Progress Success Alert

---

backend/src/database/entities/personnel/personnel.entity.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/personnel.ro.ts
frontend/src/common/constants.ts
frontend/src/components/profile/details/Detail.tsx
frontend/src/components/profile/details/DetailsSection.tsx
frontend/src/components/profile/details/ProfileDetails.tsx
frontend/src/components/profile/sections-roles/MemberItemList.tsx
frontend/src/components/profile/skills-certifications/SkillsAndCertifications.tsx
frontend/src/components/tabs/MemberProfileDetails.tsx
frontend/src/components/tabs/MemberTraining.tsx
frontend/src/hooks/coordinatorProfileData.tsx
frontend/src/hooks/memberProfileData.tsx
frontend/src/pages/SplashPage.tsx
frontend/src/pages/profile/MemberProfile.tsx
frontend/src/pages/profile/types.ts

[TC-1112](https://bcdevex.atlassian.net/browse/TC-1112)
Remaining todos:
- Hiding of banner when necessary

[TC-1112] Feat/chips frontend

---

backend/src/bcws/bcws.controller.ts
backend/src/emcr/emcr.controller.ts
backend/src/personnel/personnel.service.ts
frontend/src/components/profile/details/ProfileDetails.tsx
frontend/src/components/profile/forms/constants.ts
frontend/src/components/profile/forms/memberFormConfig.tsx
frontend/src/components/recommitment/RecommitmentFormBase.tsx
frontend/src/components/recommitment/SupervisorForm.tsx
frontend/src/components/tabs/MemberProfileDetails.tsx

[TC-1057](https://bcdevex.atlassian.net/browse/TC-1057)
Objective:
Allow coordinator to update email
Remove gov.bc.ca limitation
Update chips issues to empty when member is updated

[TC-1057] update email, chips issues

---

frontend/src/pages/intake-form/pages/Review.tsx

[TC-1122](https://bcdevex.atlassian.net/browse/TC-1122)
Objective:

[TC-1122] review screen values

---

frontend/src/pages/intake-form/pages/Complete.tsx
frontend/src/pages/intake-form/utils/tab-fields.tsx

[TC-1123] Complete Screen

---

backend/src/intake-form/intake-form.service.ts
backend/src/intake-form/types.ts

[TC-1036](https://bcdevex.atlassian.net/browse/TC-1036)
Objective:

[TC-1036] make chips request when intake form is creating

---

backend/src/common/enums/bcws/language.enum.ts
backend/src/common/enums/travel-preference.enum.ts
backend/src/intake-form/intake-form.service.ts
backend/src/intake-form/types.ts
frontend/src/pages/intake-form/FormWrapper.tsx
frontend/src/pages/intake-form/IntakeForm.tsx
frontend/src/pages/intake-form/components/FieldGroup.tsx
frontend/src/pages/intake-form/constants/initial-values.ts
frontend/src/pages/intake-form/constants/types.ts
frontend/src/pages/intake-form/constants/validation.ts
frontend/src/pages/intake-form/fields/CheckBoxGroupField.tsx
frontend/src/pages/intake-form/fields/MultiSelectField.tsx
frontend/src/pages/intake-form/fields/RadioGroupField.tsx
frontend/src/pages/intake-form/fields/SelectField.tsx
frontend/src/pages/intake-form/pages/Experiences.tsx
frontend/src/pages/intake-form/pages/PersonalDetails.tsx
frontend/src/pages/intake-form/pages/Review.tsx
frontend/src/pages/intake-form/utils/helpers.tsx
frontend/src/pages/intake-form/utils/tab-fields.tsx

Objective:
- bcws roles submission/validation

[FIX] bcws roles on intake form

---

backend/src/views/blocks/member-steps-followup.njk
backend/src/views/blocks/member-steps.njk
backend/src/views/blocks/parq.njk
backend/src/views/member/member-no-response.njk

[TC-967](https://bcdevex.atlassian.net/browse/TC-967)
Objective:
Fix some email content
[TC-967]: https://bcdevex.atlassian.net/browse/TC-967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-967] some wording on emails

---

backend/src/intake-form/intake-form.service.ts
frontend/src/pages/intake-form/constants/validation.ts
frontend/src/pages/intake-form/fields/CheckBoxGroupField.tsx
frontend/src/pages/intake-form/fields/CheckboxField.tsx

[FIX] EMCR only validation

---

backend/src/intake-form/intake-form.service.ts

Objective:
Fix CHIPS on the intake form to check for data

[FIX] check for data as well

---

backend/src/common/enums/union-membership.enum.ts
backend/src/database/migrations/1742807929542-other-union-migration.ts
backend/src/personnel/personnel.service.ts
frontend/src/common/enums/union-membership.enum.ts

Objective:
Add "other" option for union membership

[FIX] add other union membership

---

frontend/src/pages/SplashPage.tsx
frontend/src/pages/intake-form/constants/enums.tsx
frontend/src/pages/intake-form/pages/Program/Program.tsx
frontend/src/pages/intake-form/pages/Program/components.tsx
frontend/src/pages/intake-form/utils/tab-fields.tsx

Made all the links have the underline + fixed hrefs for some of the links.

[TC-1128] fix: link styling and hrefs

---

frontend/src/pages/intake-form/pages/Program/Program.tsx
frontend/src/pages/intake-form/pages/Program/components.tsx

[FIX] form font

---

backend/src/intake-form/intake-form.service.ts
backend/src/personnel/personnel.service.ts

Objective:
When CHIPS errors out, do not error out the fully process
Set personnel properly

[FIX] intake personnel error, handle chips error

---

backend/src/jobs/chips.ts

Objective:
It wasn't setting because I didn't check success / data correctly

[FIX] set CHIPS profile missing properly

---

frontend/src/pages/intake-form/utils/tab-fields.tsx

[FIX] supervisor placeholder

---

Makefile
backend/src/views/test/intake/confirmation.njk
frontend/src/pages/intake-form/pages/Program/components.tsx

Objective:
- email template added to the tests directory

[FIX] added new template to test directory

---

backend/src/intake-form/intake-form.service.ts
frontend/src/components/ui/Banner.tsx
frontend/src/pages/SplashPage.tsx
frontend/src/pages/intake-form/IntakeForm.tsx
frontend/tailwind.config.cjs

Objective:
- splash page
- banner on program selection

[FIX] UI bug  fixes

---

frontend/src/hooks/useIntakeForm.tsx

[FIX]  remove extra fields from form submission

---

frontend/src/components/tabs/Availability.tsx

[TC-1080](https://bcdevex.atlassian.net/browse/TC-1080)
[TC-1092](https://bcdevex.atlassian.net/browse/TC-1092)
[TC-1118](https://bcdevex.atlassian.net/browse/TC-1118)
Objective:

[FIX] recommitment banner fixes

---

backend/src/emcr/emcr.controller.ts
frontend/src/components/profile/details/ProfileDetails.tsx
frontend/src/components/profile/details/RecommitmentDetails.tsx
frontend/src/hooks/usePersonnel.tsx
frontend/src/hooks/useRecommitment.tsx
frontend/src/pages/profile/Profile.tsx

[TC-1113](https://bcdevex.atlassian.net/browse/TC-1113)
Objective:

[TC-1113] pending auto update

---

frontend/src/pages/intake-form/FormWrapper.tsx
frontend/src/pages/intake-form/IntakeForm.tsx
frontend/src/pages/intake-form/fields/SelectField.tsx
frontend/src/pages/intake-form/pages/Experiences.tsx
frontend/src/pages/intake-form/pages/Review.tsx
frontend/src/pages/intake-form/utils/tab-fields.tsx

Objective:
[https://emcr.atlassian.net/browse/TC-1161](https://emcr.atlassian.net/browse/TC-1161)
[https://emcr.atlassian.net/browse/TC-1162](https://emcr.atlassian.net/browse/TC-1162)
[https://emcr.atlassian.net/browse/TC-1167](https://emcr.atlassian.net/browse/TC-1167)

[FIX] UI fix 3

---

backend/src/intake-form/intake-form.service.ts

Objective:
- removing the initial values for BCWS if submitting (second time) for EMCR and vice versa

[FIX] remove unused fields from formData on second submission

---

frontend/src/components/layout/private/Layout.tsx
frontend/src/components/profile/details/ProfileDetails.tsx
frontend/src/pages/intake-form/IntakeForm.tsx

[TC-1155](https://bcdevex.atlassian.net/browse/TC-1155)
Objective:

[TC-1155] Scroll top intake form

---

frontend/src/pages/intake-form/IntakeForm.tsx
frontend/src/pages/intake-form/pages/Review.tsx
frontend/src/pages/intake-form/utils/tab-fields.tsx

[FIX] fix banner logic on form

---

backend/src/intake-form/intake-form.service.ts
frontend/src/hooks/useIntakeForm.tsx
frontend/src/pages/intake-form/constants/initial-values.ts
frontend/src/pages/intake-form/constants/types.ts

[FIX] Fix submission

---

frontend/src/components/filters/date-picker/MonthSelector.tsx
frontend/src/components/filters/date-picker/YearSelector.tsx
frontend/src/pages/intake-form/fields/SingleDateHeader.tsx

Objective:
Calendar selections were triggering early submissions

[FIX] prevent day picker from submitting

---

frontend/src/components/profile/sections-roles/roles.ts
frontend/src/pages/intake-form/components/Modal.tsx

Description:
- Changed roles to BCWS according to Figma
- Changed font according to Figma
- Hid the scrollbar according to ticket request
Screenshorts:
1) Sections
2) Scroll & Font

[TC-1173] fix: change roles, address ui issues

---

frontend/src/components/filters/date-picker/constants.ts
frontend/src/components/profile/skills-certifications/MemberSkillsAndCertifications.tsx
frontend/src/components/tabs/Availability.tsx
frontend/src/hooks/useIntakeForm.tsx
frontend/src/pages/intake-form/pages/PersonalDetails.tsx
frontend/src/pages/intake-form/utils/tab-fields.tsx

[TC-1182](https://bcdevex.atlassian.net/browse/TC-1182)
[TC-1174](https://bcdevex.atlassian.net/browse/TC-1174)
[TC-1190](https://bcdevex.atlassian.net/browse/TC-1190)
[TC-1189](https://bcdevex.atlassian.net/browse/TC-1189)
[TC-1179](https://bcdevex.atlassian.net/browse/TC-1179)
[TC-1187](https://bcdevex.atlassian.net/browse/TC-1187)
Objective:

[FIX] Various tickets

---

frontend/src/pages/intake-form/pages/Program/components.tsx

Description:
- Fixed links according to the client's specifications.
Screenshots:

[TC-1138] fix: links

---

frontend/src/pages/intake-form/utils/tab-fields.tsx

Description:
- Changed text according to client's request
- Changed the color of <p> elements to match figma
- Formatting

[TC-1177] fix: change text

---

backend/src/common/enums/bcws/skills-certifications.enum.ts
backend/src/database/migrations/1743013336475-migration.ts
frontend/src/common/enums/tools.enum.ts
frontend/src/components/filters/classes.ts
frontend/src/pages/SplashPage.tsx
frontend/src/pages/intake-form/FormWrapper.tsx
frontend/src/pages/intake-form/constants/validation.ts
frontend/src/pages/intake-form/fields/MultiSelectField.tsx
frontend/src/pages/intake-form/fields/SelectField.tsx
frontend/src/pages/intake-form/fields/TextField.tsx

Objective:
- Landing page text
- [1148](https://emcr.atlassian.net/browse/1148)
- Proficiency Levels / Expiry in skills:
- [1193](https://emcr.atlassian.net/browse/1193)
- MultiSelect box checked items:
- [1184](https://emcr.atlassian.net/browse/1184)
- Hover effect on dropdowns:
- [1170](https://emcr.atlassian.net/browse/1170)
- Fix first aid name in drop down: 
- [1017](https://emcr.atlassian.net/browse/1017)

[FIX] UI fix 4

---

backend/src/intake-form/intake-form.service.ts
backend/src/views/blocks/resources.njk
backend/src/views/intake/confirmation.njk
backend/src/views/layout.njk

Description:
- Changed the confirmation email template according to the client's request
Notes: can't test it on my end at the moment, submitting a draft PR just in case.

[TC-1158] feat: confirmation email layout

---

frontend/src/pages/Unauthorized.tsx
frontend/src/pages/intake-form/IntakeForm.tsx
frontend/src/pages/intake-form/components/FormButtonNavigation.tsx
frontend/src/pages/intake-form/components/FormStepper.tsx
frontend/src/pages/intake-form/constants/validation.ts
frontend/src/pages/intake-form/fields/FormField.tsx
frontend/src/pages/intake-form/fields/MultiSelectField.tsx

Objective:
- [Review step validation](https://emcr.atlassian.net/browse/TC-1178)
- [Unauth navigation](https://emcr.atlassian.net/browse/TC-1169)
- [Submit Button](https://emcr.atlassian.net/browse/TC-1175)

[FIX] Submission Button + Review Step Validation 

---

frontend/src/pages/intake-form/FormWrapper.tsx
frontend/src/pages/intake-form/pages/Review.tsx

[FIX] certs on review + functions width

---

frontend/src/hooks/useIntakeForm.tsx
frontend/src/pages/Unauthorized.tsx
frontend/src/pages/intake-form/FormWrapper.tsx
frontend/src/pages/intake-form/IntakeForm.tsx
frontend/src/pages/intake-form/fields/FormField.tsx
frontend/src/providers/StepperContext.tsx

[TC-1171](https://bcdevex.atlassian.net/browse/TC-1171)
Objective:
- Resolves early field validation

[TC-1171]/[TC-1169]/[TC-1196] BUGFIX: early field validation trigger, redirect, program selection 

---

frontend/src/pages/intake-form/pages/Complete.tsx

[TC-1169](https://bcdevex.atlassian.net/browse/TC-1169)
Objective:

[TC-1169] Unauth screen nav from form

---

frontend/src/common/enums/ministry.enum.ts

Objective:
- added "Other" ministry option to the form

[CHORE] added other as ministry option

---

frontend/src/pages/intake-form/IntakeForm.tsx
frontend/src/pages/intake-form/constants/types.ts
frontend/src/pages/intake-form/constants/validation.ts
frontend/src/pages/intake-form/fields/FormField.tsx
frontend/src/pages/intake-form/fields/RadioGroupField.tsx
frontend/src/pages/intake-form/utils/tab-fields.tsx

[TC-1172](https://bcdevex.atlassian.net/browse/TC-1172)
Objective:
- Fixes home location + program validation message visibility
- change font color
- button submits single click
- fix splash button

[TC-1172] Program validation + Home Location

---

frontend/src/hooks/useIntakeForm.tsx
frontend/src/pages/intake-form/IntakeForm.tsx
frontend/src/pages/intake-form/components/FormButtonNavigation.tsx

[TC-1202](https://bcdevex.atlassian.net/browse/TC-1202)
Objective:
- Bugfix for button not registering first click

[TC-1202] submit button not registering first click

---

frontend/src/components/ui/Banner.tsx
frontend/src/components/ui/Icons.tsx
frontend/src/components/ui/classes.ts
frontend/src/pages/SplashPage.tsx
frontend/src/pages/intake-form/components/Accordion.tsx
frontend/src/pages/intake-form/components/FieldGroup.tsx
frontend/src/pages/intake-form/pages/Complete.tsx
frontend/tailwind.config.cjs

[TC-1137](https://bcdevex.atlassian.net/browse/TC-1137)
Objective:

[TC-1137] UI fixes

---

backend/src/bcws/bcws.controller.ts
backend/src/emcr/emcr.controller.ts
frontend/src/pages/dashboard/Dashboard.tsx

[FIX] remove csv download to deploy to prod (temp)

---

backend/src/bcws/bcws.controller.ts
backend/src/emcr/emcr.controller.ts
frontend/src/pages/dashboard/Dashboard.tsx

Objective:
- adding the download button back to main

[CHORE] reverting download button remove

---

.github/workflows/ci-deploy.yaml

[TC-0000](https://bcdevex.atlassian.net/browse/TC-0000)
Objective:

[CHORE] zap test

---

frontend/src/components/profile/forms/memberFormConfig.tsx
frontend/src/pages/SplashPage.tsx
frontend/src/pages/intake-form/pages/Complete.tsx
frontend/src/routes/PrivateRoute.tsx
frontend/src/utils/keycloak.ts

[CORE-12](https://emcr.atlassian.net/browse/CORE-12)
Objective:
Display and save Liaison Phone number:

[FIX]Core-12: Cannot save changes member profile

---

frontend/src/hooks/helpers.ts

changes
- corrected totalAvailableDays logic to read how many days of a given availabilityType within a persons date range.
- updated totalAvailableDays name to totalDaysOfAvailabilityType to better describe what the function does.

CORE-17 User Days of Availability bug fix
