backend/package-lock.json
backend/package.json
backend/src/app.controller.ts
backend/src/app.module.ts
backend/src/auth/auth.controller.ts
backend/src/auth/auth.guard.ts
backend/src/auth/auth.module.ts
backend/src/auth/const.ts
backend/src/auth/interface.ts
backend/src/auth/metadata.ts
backend/src/auth/public.decorator.ts
backend/src/main.ts
backend/src/private/private.controller.spec.ts
backend/src/private/private.controller.ts
backend/src/private/private.module.ts
backend/src/swagger.ts
frontend/src/hooks/useGetHealth.tsx
frontend/src/pages/AppHealth.tsx
frontend/src/pages/index.ts
frontend/src/routes/Routes.tsx
frontend/src/services/health.tsx
frontend/src/services/keycloak.ts
keycloak/default.json

- Checking auth token on all routes that are not annotated with the public decorator
- Validating auth token
- Checking Reflector to see if route is annotated with a Roles decorator
- Validating user assigned role if the current route requires a role

[TC-0059] Auth Guard

---

backend/src/database/database.module.ts
backend/src/database/entities/personnel-function-experience.entity.ts

[TC-58](https://bcdevex.atlassian.net/browse/TC-58)
Objective:
Use composite key instead of id for experiences
Drop dropschema, that was for testing
[TC-58]: https://bcdevex.atlassian.net/browse/TC-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-58] use composite key for experience

---

openshift/client.bc.yml
openshift/server.bc.yml

[TC-3](https://bcdevex.atlassian.net/browse/TC-3)
Objective:
This is the current quota for builds:
I think this is okay since the builds do not run concurrently, we can make this request appropriately.
[TC-3]: https://bcdevex.atlassian.net/browse/TC-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHORE] increase build resources

---

frontend/index.html
frontend/src/components/table/body/TableBodyCell.tsx

[TC-269](https://bcdevex.atlassian.net/browse/TC-269)
Objective:
base href fixes the issue where a blank screen loads when trying to open profile in a new tab / refreshing
_blank fixes typo
[TC-269]: https://bcdevex.atlassian.net/browse/TC-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX] new tab

---

backend/src/database/entities/personnel-function-experience.entity.ts
backend/src/personnel/personnel.service.ts
backend/src/personnel/ro/experience.ro.ts
frontend/src/hooks/useFunctions.tsx
frontend/src/pages/dashboard/constants.ts
frontend/src/pages/profile/Profile.tsx
frontend/src/pages/profile/ProfileFunctions.tsx
frontend/tailwind.config.cjs

[TC-372](https://bcdevex.atlassian.net/browse/TC-372)
Objective:
Display functions / experience levels in profile page
Designs from [Figma Prototype](https://www.figma.com/proto/EsuYOEyGPvIVDEFGnYCJ2f/CoCo-EMCR%3A-TEAMS-Redesign?page-id=2349%3A12933&type=design&node-id=2358-47218&viewport=-237%2C-1598%2C0.2&t=kxYM1ZJE08ZzOdWh-1&scaling=scale-down&starting-point-node-id=2358%3A47218)
[TC-372]: https://bcdevex.atlassian.net/browse/TC-372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-372] get and display different experiences

---

frontend/src/pages/profile/ProfileDetails.tsx
frontend/src/pages/profile/ProfileEditForm.tsx

[TC-0365](https://bcdevex.atlassian.net/browse/TC-0365)
Objective:
- showing personnel.dateJoined on profile and edit form (bugfix)
- TODO: is application date the same as date joined?

[TC-365]: update profile view to show date joined

---

backend/src/common/bcws-seed.ts

Objective:
- fix spelling error which was preventing seeder from running

[FIX] fixed BCWS seeder

---

frontend/src/hooks/useFilters.tsx

[TC-643](https://bcdevex.atlassian.net/browse/TC-643)
Objective:
This feels like the right solution, since:
1. The library we're using seems impossible to get a `to` date without a `from` date and
2. On the backend, we only add the FROM and TO to the query if both are present
[TC-643]: https://bcdevex.atlassian.net/browse/TC-643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-643] use from date in the absence of to date for search filters

---

frontend/src/pages/profile/SchedulerPopUp.tsx

[TC-688](https://bcdevex.atlassian.net/browse/TC-688)
Objective:
By removing the default, the user should be less confused when they do the first click on the calendar; the first click should always reflect the date they intend to start in.
[TC-688]: https://bcdevex.atlassian.net/browse/TC-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-688] removing default when Update Availability clicked

---

Makefile
backend/src/jobs/automated_reminders.ts
backend/src/jobs/end_recommitment.ts
backend/src/jobs/start_recommitment.ts
openshift/client.dc.yml
openshift/cron-end-recommitment.yml
openshift/cron-notifications.yml
openshift/cron-start-recommitment.yml
openshift/server.dc.yml

Objective:
- job should be completed after running 
- updated cpu limits:
```
name      limit x  pods  total 
--------------------------------
patroni -   50  x  3  =  150 
backup  -   50  x  1  =  50
cron    -   20  x  1  =  20
client  -   20  x  3  =  60
server  -   50  x  3  =  150
------------------------------
430
```

[FIX] Crons timeout

---

backend/src/personnel/personnel.service.ts
frontend/src/hooks/useFilters.tsx

[TC-821](https://bcdevex.atlassian.net/browse/TC-821)
Objective:
Fixes a frontend bug when selecting date filters, it seems to deselect Availability Type and have some other funky behavior
Fixes availability filter bug where it now gets personnel that have half or more days available from the selection
TODO: Frontend to display "Available 3 of 6 days"
[TC-821]: https://bcdevex.atlassian.net/browse/TC-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-821] Availability Filter bug

---

backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/audit/audit.module.ts
backend/src/audit/audit.service.ts
backend/src/audit/subscribers/bcws-personnel.subscriber.ts
backend/src/audit/subscribers/emcr-personnel.subscriber.ts
backend/src/audit/subscribers/personnel.subscriber.ts
backend/src/audit/subscribers/recommitment.subscriber.ts
backend/src/auth/auth.guard.ts
backend/src/bcws/bcws.module.ts
backend/src/database/entities/audit.entity.ts
backend/src/database/migrations/1737094259888-audit-log-migration.ts
backend/src/emcr/emcr.module.ts
backend/src/personnel/personnel.controller.ts
backend/src/personnel/personnel.module.ts
backend/src/recommitment/recommitment.module.ts
backend/src/recommitment/recommitment.service.ts

[TC-816](https://bcdevex.atlassian.net/browse/TC-816)
Objective:
Establish an audit log for when Personnel / EMCR / BCWS / Availability / Recommitment are changed / created
Ensure members can edit only their own availability (see personnel.controller changes)
TO TEST: Form submission and audit logs from there
[TC-816]: https://bcdevex.atlassian.net/browse/TC-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-816] Audit Log

---

backend/src/audit/audit.service.ts
backend/src/audit/subscribers/bcws-personnel.subscriber.ts
backend/src/audit/subscribers/emcr-personnel.subscriber.ts
backend/src/audit/subscribers/personnel.subscriber.ts
backend/src/audit/subscribers/recommitment.subscriber.ts

clsService.set isn't working from jobs correctly, so we ensure we only use it when we are in the application lifecycle itself, not in jobs
Objective:

[FIX] only set cls in guards

---

backend/src/database/entities/emcr/emcr-personnel.entity.ts
backend/src/personnel/personnel.service.ts
docker-compose.yml
frontend/src/components/profile/banners/RecommitmentDashBanner.tsx
frontend/src/components/recommitment/InitialRecommitmentDropdown.tsx
frontend/src/components/recommitment/RecommitmentFormBase.tsx
frontend/src/components/recommitment/SupervisorForm.tsx
frontend/src/components/table/body/TableBodyCell.tsx
frontend/src/hooks/useMemberProfile.tsx
frontend/src/pages/profile/MemberProfile.tsx

[TC-924](https://bcdevex.atlassian.net/browse/TC-924)
[TC-920](https://bcdevex.atlassian.net/browse/TC-920)
Objective:
[TC-924]: https://bcdevex.atlassian.net/browse/TC-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TC-920]: https://bcdevex.atlassian.net/browse/TC-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-924] fix recommitment program on member profile and dashboard banner

---

frontend/src/components/recommitment/RecommitmentFormBase.tsx
frontend/src/components/recommitment/UnableToJoin.tsx
frontend/src/hooks/profileData.tsx

[TC-910](https://bcdevex.atlassian.net/browse/TC-910)
If declining both, separate reasons
Objective:
[TC-910]: https://bcdevex.atlassian.net/browse/TC-910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-910] Separate unable to join

---

frontend/src/components/recommitment/RecommitmentFormBase.tsx

[TC-907](https://bcdevex.atlassian.net/browse/TC-907)
Objective:
If user is only in one program, only show unable to join for that
[TC-907]: https://bcdevex.atlassian.net/browse/TC-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FIX] unable to join one program

---

backend/src/mail/mail.dto.ts
backend/src/mail/mail.service.ts
backend/src/recommitment/recommitment.service.ts

[FIX] mail service checks

---

frontend/src/components/recommitment/InitialRecommitmentDropdown.tsx
frontend/src/components/recommitment/UnableToJoin.tsx

[TC-903](https://bcdevex.atlassian.net/browse/TC-903)
[TC-905](https://bcdevex.atlassian.net/browse/TC-905)
Objective:
100 character limit for other reasons
Warning text when declining
[TC-903]: https://bcdevex.atlassian.net/browse/TC-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TC-905]: https://bcdevex.atlassian.net/browse/TC-905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-903] Declining Text

---

backend/src/recommitment/recommitment.service.ts
backend/src/views/blocks/member-program.njk
backend/src/views/blocks/member-steps-followup.njk
backend/src/views/blocks/steps.njk
backend/src/views/layout.njk
backend/src/views/member/member-annual-reminder.njk
backend/src/views/member/member-approved.njk
backend/src/views/member/member-declined.njk
backend/src/views/member/member-denied.njk
backend/src/views/member/member-follow-up.njk
backend/src/views/member/member-no-response.njk
backend/src/views/member/member-reactivate.njk
backend/src/views/member/member-supervisor-no-response.njk
backend/src/views/supervisor/supervisor-follow-up-reminder.njk
backend/src/views/supervisor/supervisor-request.njk
frontend/src/hooks/useRecommitment.tsx

[TC-962](https://bcdevex.atlassian.net/browse/TC-962)
Email template for reactivating member
Timing changes for using end date vs. reinitiation end date
Use of PST date for the above
Changing other templates to "CORE Team"
Differentiate between member steps and member follow up steps as Chevonne mentioned they are intentionally different
[TC-962]: https://bcdevex.atlassian.net/browse/TC-962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TC-962] reactivation email template

---

backend/src/bcws/dto/helpers.ts

Ticket:
https://emcr.atlassian.net/browse/TC-1079
Description:
- added `dateApproved` to `BcwsUpdateAdapter` so that the date gets updated properly
Screenshots:
Before approval:
After Approval:

[TC-1079] fix: add dateApproved to BcwsUpdateAdapter

---

frontend/src/hooks/commonProfileData.tsx

Ticket:
https://emcr.atlassian.net/browse/TC-925
Description:
- Added a default empty `MembershipDetails` object that applies to the personnel who don't have entries in the `recommitment` table
- This makes sure that the placeholder empty data is still displayed, otherwise the whole section is empty and it was confusing for the client
Screenshots:
1) Before:
2) After:
3) With data present in `recommitment` for that `personnel_id`:

[TC-925] fix: add default placeholder for pending

---

frontend/src/components/ui/Table.tsx

Ticket:
https://emcr.atlassian.net/browse/TC-980
Description:
- Added a loader icon for data that is still being processed on the dashboard
- The loader goes away after the data is loaded
Screenshots:
QA Instructions:
- In order to see the loader, add `true` to the following line in `Dashboard.tsx`:

[TC-980] fix: add loader to dashboard

---

frontend/src/pages/SplashPage.tsx

Ticket:
https://emcr.atlassian.net/browse/TC-972
Description:
- Added some missing text elements to the splash screen
- Made sure they look like the figma designs
Screenshots:
Note:
Need to insert links to the `<a>` elements still, pending on Chevonne.

[TC-972] fix: add missing elements for splash screen

---

frontend/src/common/enums/status.enum.ts

Renamed the enum according to the client's request.

[TC-949] Rename Missed Recommitment -> Missed Deadline

---

frontend/src/components/toggle/Toggle.tsx

Description:
- Added a check to hide the tooltip when the recommitment cycle is inactive
Screenshots:
1) Cycle is active:
2) Cycle is inactive:

[TC-1102] fix: hide tooltip if not recommitmentCycle

---

backend/package-lock.json
backend/package.json
backend/src/bcws/bcws.controller.ts
backend/src/bcws/bcws.service.ts
backend/src/common/enums/bcws/csv-headers.ts
backend/src/common/enums/bcws/index.ts
backend/src/common/enums/emcr/csv-headers.ts
backend/src/common/enums/emcr/index.ts
backend/src/emcr/emcr.controller.ts
backend/src/emcr/emcr.service.ts
frontend/src/hooks/useExportToCSV.tsx
frontend/src/pages/dashboard/Dashboard.tsx

Implements functionality for exporting of ECMR and BCWS personnel information as CSV-formatted downloadable files.  This process involves the following adjustments:
1. Addition of new methods to EMCR and BCWS services which query their respective TypeORM entities and join detailed personnel, location and recommitment information from their respective database tables.
2. Addition of new methods to EMCR and BCWS controllers which receive these service methods, convert the output to CSV format using the NPM library json-2-csv, and return streamable file versions of these outputs for download.
3. To make column headers more readable, new "enumerations" (technically consts) have been added to the enums folders for EMCR and BCWS which are used in the controller methods to rename the internal DB …

[TC-974] Enable Export of Data From Database

---

backend/src/views/intake/confirmation.njk

Description: changed the wording to the following

[TC-1158] fix: link wording

---

backend/src/database/datasource.ts
backend/src/personnel/personnel.service.ts
frontend/src/components/table/classes.ts

[TC-1200](https://bcdevex.atlassian.net/browse/TC-1200)
Objective:
Currently if you are searching for a member by an available date range, the member will only show up if the confirmed until date is after the the [query.to](http://query.to/) date. We allow partial matches so this should be changed to include users whose confirmed until date is greater than or equal to the query.from date.

[TC-1200] adjustment to availability query
